export const simpleIngredients = [
  { "name": "Apple", "calories": 52, "protein": 0, "carbs": 14, "fat": 0, "fiber": 2 },
  { "name": "Banana", "calories": 89, "protein": 1, "carbs": 23, "fat": 0, "fiber": 3 },
  { "name": "Orange", "calories": 47, "protein": 1, "carbs": 12, "fat": 0, "fiber": 2 },
  { "name": "Salmon", "calories": 206, "protein": 22, "carbs": 0, "fat": 13, "fiber": 0 },
  { "name": "Chicken Breast", "calories": 165, "protein": 31, "carbs": 0, "fat": 4, "fiber": 0 },
  { "name": "Beef", "calories": 250, "protein": 26, "carbs": 0, "fat": 15, "fiber": 0 },
  { "name": "Egg", "calories": 78, "protein": 6, "carbs": 1, "fat": 5, "fiber": 0 },
  { "name": "Milk", "calories": 61, "protein": 3, "carbs": 5, "fat": 3, "fiber": 0 },
  { "name": "Yogurt", "calories": 59, "protein": 10, "carbs": 3, "fat": 0, "fiber": 0 },
  { "name": "Cheese", "calories": 402, "protein": 25, "carbs": 1, "fat": 33, "fiber": 0 },
  { "name": "Bread", "calories": 265, "protein": 9, "carbs": 49, "fat": 3, "fiber": 3 },
  { "name": "Rice", "calories": 130, "protein": 3, "carbs": 28, "fat": 0, "fiber": 0 },
  { "name": "Pasta", "calories": 131, "protein": 5, "carbs": 25, "fat": 1, "fiber": 2 },
  { "name": "Potato", "calories": 77, "protein": 2, "carbs": 17, "fat": 0, "fiber": 2 },
  { "name": "Carrot", "calories": 41, "protein": 1, "carbs": 10, "fat": 0, "fiber": 3 },
  { "name": "Broccoli", "calories": 34, "protein": 3, "carbs": 7, "fat": 0, "fiber": 2 },
  { "name": "Spinach", "calories": 23, "protein": 3, "carbs": 4, "fat": 0, "fiber": 3 },
  { "name": "Tomato", "calories": 18, "protein": 1, "carbs": 4, "fat": 0, "fiber": 1 },
  { "name": "Lettuce", "calories": 15, "protein": 1, "carbs": 3, "fat": 0, "fiber": 2 },
  { "name": "Cucumber", "calories": 16, "protein": 1, "carbs": 4, "fat": 0, "fiber": 1 },
  { "name": "Bell Pepper", "calories": 31, "protein": 1, "carbs": 7, "fat": 0, "fiber": 2 },
  { "name": "Onion", "calories": 40, "protein": 1, "carbs": 9, "fat": 0, "fiber": 1 },
  { "name": "Garlic", "calories": 149, "protein": 7, "carbs": 33, "fat": 1, "fiber": 2 },
  { "name": "Olive Oil", "calories": 884, "protein": 0, "carbs": 0, "fat": 100, "fiber": 0 },
  { "name": "Butter", "calories": 717, "protein": 1, "carbs": 0, "fat": 81, "fiber": 0 },
  { "name": "Peanut Butter", "calories": 588, "protein": 25, "carbs": 20, "fat": 50, "fiber": 6 },
  { "name": "Almond", "calories": 579, "protein": 21, "carbs": 22, "fat": 50, "fiber": 13 },
  { "name": "Walnut", "calories": 654, "protein": 15, "carbs": 14, "fat": 66, "fiber": 7 },
  { "name": "Oats", "calories": 389, "protein": 17, "carbs": 66, "fat": 7, "fiber": 11 },
  { "name": "Beans", "calories": 127, "protein": 9, "carbs": 23, "fat": 0, "fiber": 6 },
  { "name": "Lentils", "calories": 116, "protein": 9, "carbs": 20, "fat": 0, "fiber": 8 },
  { "name": "Pea", "calories": 81, "protein": 5, "carbs": 14, "fat": 0, "fiber": 3 },
  { "name": "Corn", "calories": 86, "protein": 3, "carbs": 19, "fat": 1, "fiber": 2 },
  { "name": "Avocado", "calories": 160, "protein": 2, "carbs": 9, "fat": 15, "fiber": 7 },
  { "name": "Blueberry", "calories": 57, "protein": 1, "carbs": 14, "fat": 0, "fiber": 2 },
  { "name": "Strawberry", "calories": 32, "protein": 1, "carbs": 8, "fat": 0, "fiber": 2 },
  { "name": "Raspberry", "calories": 52, "protein": 1, "carbs": 12, "fat": 1, "fiber": 7 },
  { "name": "Grape", "calories": 67, "protein": 1, "carbs": 17, "fat": 0, "fiber": 1 },
  { "name": "Watermelon", "calories": 30, "protein": 1, "carbs": 8, "fat": 0, "fiber": 0 },
  { "name": "Cantaloupe", "calories": 34, "protein": 1, "carbs": 8, "fat": 0, "fiber": 1 },
  { "name": "Pineapple", "calories": 50, "protein": 0, "carbs": 13, "fat": 0, "fiber": 1 },
  { "name": "Mango", "calories": 60, "protein": 1, "carbs": 15, "fat": 0, "fiber": 2 },
  { "name": "Papaya", "calories": 43, "protein": 1, "carbs": 11, "fat": 0, "fiber": 2 },
  { "name": "Kiwi", "calories": 61, "protein": 1, "carbs": 15, "fat": 0, "fiber": 3 },
  { "name": "Lemon", "calories": 29, "protein": 1, "carbs": 9, "fat": 0, "fiber": 3 },
  { "name": "Lime", "calories": 30, "protein": 1, "carbs": 11, "fat": 0, "fiber": 3 },
  { "name": "Peach", "calories": 39, "protein": 1, "carbs": 10, "fat": 0, "fiber": 1 },
  { "name": "Pear", "calories": 57, "protein": 0, "carbs": 15, "fat": 0, "fiber": 3 },
  { "name": "Plum", "calories": 46, "protein": 1, "carbs": 11, "fat": 0, "fiber": 2 },
  { "name": "Cherry", "calories": 63, "protein": 1, "carbs": 16, "fat": 0, "fiber": 2 },
  { "name": "Blackberry", "calories": 43, "protein": 1, "carbs": 10, "fat": 1, "fiber": 5 },
  { "name": "Coconut", "calories": 354, "protein": 3, "carbs": 15, "fat": 33, "fiber": 9 },
  { "name": "Pork", "calories": 242, "protein": 27, "carbs": 0, "fat": 14, "fiber": 0 },
  { "name": "Turkey", "calories": 189, "protein": 29, "carbs": 0, "fat": 8, "fiber": 0 },
  { "name": "Tuna", "calories": 144, "protein": 30, "carbs": 0, "fat": 1, "fiber": 0 },
  { "name": "Shrimp", "calories": 99, "protein": 24, "carbs": 0, "fat": 0, "fiber": 0 },
  { "name": "Cod", "calories": 82, "protein": 18, "carbs": 0, "fat": 1, "fiber": 0 },
  { "name": "Tilapia", "calories": 96, "protein": 20, "carbs": 0, "fat": 1, "fiber": 0 },
  { "name": "Ground Turkey", "calories": 189, "protein": 26, "carbs": 0, "fat": 9, "fiber": 0 },
  { "name": "Ground Beef", "calories": 250, "protein": 25, "carbs": 0, "fat": 17, "fiber": 0 },
  { "name": "Cottage Cheese", "calories": 98, "protein": 11, "carbs": 4, "fat": 5, "fiber": 0 },
  { "name": "Mozzarella", "calories": 280, "protein": 28, "carbs": 3, "fat": 17, "fiber": 0 },
  { "name": "Cheddar Cheese", "calories": 403, "protein": 23, "carbs": 4, "fat": 33, "fiber": 0 },
  { "name": "Feta Cheese", "calories": 264, "protein": 14, "carbs": 4, "fat": 21, "fiber": 0 },
  { "name": "Greek Yogurt", "calories": 59, "protein": 10, "carbs": 3, "fat": 0, "fiber": 0 },
  { "name": "Honey", "calories": 304, "protein": 0, "carbs": 82, "fat": 0, "fiber": 0 },
  { "name": "Sugar", "calories": 387, "protein": 0, "carbs": 100, "fat": 0, "fiber": 0 },
  { "name": "Brown Rice", "calories": 111, "protein": 3, "carbs": 23, "fat": 1, "fiber": 2 },
  { "name": "Quinoa", "calories": 120, "protein": 4, "carbs": 21, "fat": 2, "fiber": 3 },
  { "name": "Sweet Potato", "calories": 86, "protein": 2, "carbs": 20, "fat": 0, "fiber": 3 },
  { "name": "Pumpkin", "calories": 26, "protein": 1, "carbs": 7, "fat": 0, "fiber": 1 },
  { "name": "Cauliflower", "calories": 25, "protein": 2, "carbs": 5, "fat": 0, "fiber": 2 },
  { "name": "Cabbage", "calories": 25, "protein": 1, "carbs": 6, "fat": 0, "fiber": 2 },
  { "name": "Kale", "calories": 49, "protein": 4, "carbs": 9, "fat": 1, "fiber": 2 },
  { "name": "Brussels Sprouts", "calories": 43, "protein": 4, "carbs": 8, "fat": 0, "fiber": 2 },
  { "name": "Asparagus", "calories": 20, "protein": 2, "carbs": 4, "fat": 0, "fiber": 2 },
  { "name": "Green Beans", "calories": 31, "protein": 2, "carbs": 7, "fat": 0, "fiber": 2 },
  { "name": "Celery", "calories": 16, "protein": 1, "carbs": 3, "fat": 0, "fiber": 2 },
  { "name": "Zucchini", "calories": 21, "protein": 1, "carbs": 4, "fat": 0, "fiber": 1 },
  { "name": "Eggplant", "calories": 25, "protein": 1, "carbs": 5, "fat": 0, "fiber": 3 },
  { "name": "Mushroom", "calories": 22, "protein": 3, "carbs": 3, "fat": 0, "fiber": 0 },
  { "name": "Beet", "calories": 43, "protein": 2, "carbs": 10, "fat": 0, "fiber": 2 },
  { "name": "Radish", "calories": 16, "protein": 1, "carbs": 3, "fat": 0, "fiber": 2 },
  { "name": "Turnip", "calories": 36, "protein": 1, "carbs": 8, "fat": 0, "fiber": 2 },
  { "name": "Parsnip", "calories": 75, "protein": 1, "carbs": 18, "fat": 0, "fiber": 4 },
  { "name": "Whole Wheat Bread", "calories": 247, "protein": 13, "carbs": 41, "fat": 3, "fiber": 7 },
  { "name": "White Bread", "calories": 265, "protein": 9, "carbs": 49, "fat": 3, "fiber": 3 },
  { "name": "Rye Bread", "calories": 259, "protein": 9, "carbs": 48, "fat": 3, "fiber": 7 },
  { "name": "Bagel", "calories": 245, "protein": 9, "carbs": 48, "fat": 1, "fiber": 2 },
  { "name": "Cereal", "calories": 373, "protein": 7, "carbs": 81, "fat": 2, "fiber": 3 },
  { "name": "Granola", "calories": 471, "protein": 10, "carbs": 63, "fat": 21, "fiber": 7 },
  { "name": "Sunflower Seeds", "calories": 584, "protein": 21, "carbs": 20, "fat": 52, "fiber": 9 },
  { "name": "Pumpkin Seeds", "calories": 559, "protein": 30, "carbs": 11, "fat": 49, "fiber": 6 },
  { "name": "Sesame Seeds", "calories": 563, "protein": 17, "carbs": 23, "fat": 50, "fiber": 12 },
  { "name": "Flax Seeds", "calories": 534, "protein": 18, "carbs": 29, "fat": 42, "fiber": 28 },
  { "name": "Chia Seeds", "calories": 486, "protein": 17, "carbs": 42, "fat": 31, "fiber": 34 },
  { "name": "Dark Chocolate", "calories": 578, "protein": 12, "carbs": 64, "fat": 31, "fiber": 7 }
];