import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

const BASE_URL = "https://media.base44.com/images/public/69b2f15b471168c6ba346b2e/";

const IMAGES = {
  "Bench Press":              { light: "ff3b1e6ce_generated_image.png", dark: "a56809883_generated_image.png" },
  "Squat":                    { light: "89a9a5723_generated_image.png", dark: "5b9f3144f_generated_image.png" },
  "Deadlift":                 { light: "a05a27705_generated_image.png", dark: "031745dc0_generated_image.png" },
  "Shoulder Press":           { light: "5ec7dd421_generated_image.png", dark: "fb74fb204_generated_image.png" },
  "Barbell Row":              { light: "c2e0f20af_generated_image.png", dark: "c3271b4a3_generated_image.png" },
  "Pull-ups":                 { light: "3fa1c4483_generated_image.png", dark: "0e7eedcb8_generated_image.png" },
  "Dumbbell Curl":            { light: "3740665aa_generated_image.png", dark: "79be58da7_generated_image.png" },
  "Tricep Pushdown":          { light: "b380cbb71_generated_image.png", dark: "b101e6c08_generated_image.png" },
  "Leg Press":                { light: "e5ed34bb1_generated_image.png", dark: "fdba51174_generated_image.png" },
  "Lat Pulldown":             { light: "6f8cf96de_generated_image.png", dark: "dd317de70_generated_image.png" },
  "Incline Dumbbell Press":   { light: "7fc305625_generated_image.png", dark: "0d7979211_generated_image.png" },
  "Romanian Deadlift":        { light: "af092ac72_generated_image.png", dark: "c201b6db2_generated_image.png" },
  "Plank":                    { light: "e75cf94b2_generated_image.png", dark: "922f0d851_generated_image.png" },
  "Cable Fly":                { light: "f8cf84203_generated_image.png", dark: "eac12b958_generated_image.png" },
  "Hip Thrust":               { light: "dce8f4d3d_generated_image.png", dark: "a7fd8df8b_generated_image.png" },
  "Incline Bench Press":      { light: "5392a6a35_generated_image.png", dark: "b4e25c970_generated_image.png" },
  "Decline Bench Press":      { light: "43dc9e14d_generated_image.png", dark: "9eef31062_generated_image.png" },
  "Dumbbell Chest Press":     { light: "6ef9a9d1b_generated_image.png", dark: "2a3dda063_generated_image.png" },
  "Pec Deck Machine":         { light: "46e135a03_generated_image.png", dark: "68c7c26a8_generated_image.png" },
  "Push-ups":                 { light: "2dd5acf47_generated_image.png", dark: "cc32285ad_generated_image.png" },
  "Chest Dip":                { light: "4cb719dd7_generated_image.png", dark: "00f83eea5_generated_image.png" },
  "Front Squat":              { light: "9126b2610_generated_image.png", dark: "fe457ee15_generated_image.png" },
  "Leg Curl":                 { light: "18739bf48_generated_image.png", dark: "52a359698_generated_image.png" },
  "Leg Extension":            { light: "f17c41efb_generated_image.png", dark: "44d13ac5c_generated_image.png" },
  "Hack Squat":               { light: "ef0de1d21_generated_image.png", dark: "b12c5fa56_generated_image.png" },
  "Walking Lunge":            { light: "4b979a515_generated_image.png", dark: "e836d26e8_generated_image.png" },
  "Goblet Squat":             { light: "8063a59e9_generated_image.png", dark: "e96278e9b_generated_image.png" },
  "Sumo Deadlift":            { light: "8db68f7e5_generated_image.png", dark: "97f962d87_generated_image.png" },
  "Bulgarian Split Squat":    { light: "b8d56a71a_generated_image.png", dark: "d90ae69a9_generated_image.png" },
  "Lateral Raise":            { light: "90e9e7ace_generated_image.png", dark: "323b40cfd_generated_image.png" },
  "Front Raise":              { light: "79b9fc65c_generated_image.png", dark: "e42420456_generated_image.png" },
  "Rear Delt Fly":            { light: "717cd654a_generated_image.png", dark: "ed1e03fcf_generated_image.png" },
  "Face Pull":                { light: "db547b554_generated_image.png", dark: "5db1fdc07_generated_image.png" },
  "Upright Row":              { light: "6fb41e799_generated_image.png", dark: "4ad33d64f_generated_image.png" },
  "Arnold Press":             { light: "4ac11f2c6_generated_image.png", dark: "8af2f322e_generated_image.png" },
  "Dumbbell Shoulder Press":  { light: "b356a3593_generated_image.png", dark: "4c4354eaf_generated_image.png" },
  "Cable Lateral Raise":      { light: "4f959c686_generated_image.png", dark: "5f6e6e169_generated_image.png" },
  "Barbell Curl":             { light: "42f874d2e_generated_image.png", dark: "9a4c3c985_generated_image.png" },
  "Hammer Curl":              { light: "ee8f3250a_generated_image.png", dark: "c8b5e8e1e_generated_image.png" },
  "Cable Curl":               { light: "70610dbc3_generated_image.png", dark: "f1976f821_generated_image.png" },
  "Preacher Curl":            { light: "7f9d016b4_generated_image.png", dark: "a0085ba96_generated_image.png" },
  "Concentration Curl":       { light: "7d5912ee2_generated_image.png", dark: "50da77f96_generated_image.png" },
  "Incline Dumbbell Curl":    { light: "b7ebfbb96_generated_image.png", dark: "dc0a59232_generated_image.png" },
  "Spider Curl":              { light: "9ec60bdf0_generated_image.png", dark: "bda946add_generated_image.png" },
  "Bayesian Curl":            { light: "5e288437c_generated_image.png", dark: "bec3f62f8_generated_image.png" },
  "Tricep Dip":               { light: "446c1b002_generated_image.png", dark: "ff23f27e0_generated_image.png" },
  "Close Grip Bench Press":   { light: "b5f716cc2_generated_image.png", dark: "b23c5290d_generated_image.png" },
  "Skull Crusher":            { light: "e6155751a_generated_image.png", dark: "2fc69528d_generated_image.png" },
  "Overhead Tricep Extension":{ light: "c74f280f8_generated_image.png", dark: "c0e8d5bce_generated_image.png" },
  "Dumbbell Kickback":        { light: "23a81489d_generated_image.png", dark: "873efb7fa_generated_image.png" },
  "Seated Cable Row":         { light: "78d3864ea_generated_image.png", dark: "d7d9aa2a5_generated_image.png" },
  "Single Arm Dumbbell Row":  { light: "4c9ad9fc1_generated_image.png", dark: "f62b72bd7_generated_image.png" },
  "T-Bar Row":                { light: "1e11a88d3_generated_image.png", dark: "4b490708b_generated_image.png" },
  "Machine Row":              { light: "f3495ecc2_generated_image.png", dark: "7c58bbac5_generated_image.png" },
  "Hyperextension":           { light: "e4517d825_generated_image.png", dark: "4d821e37a_generated_image.png" },
  "Machine Shoulder Press":   { light: "0c3409a59_generated_image.png", dark: "99879479a_generated_image.png" },
  "Cable Crunch":             { light: "eb9c0dd6e_generated_image.png", dark: "b407b7dd6_generated_image.png" },
  "Russian Twist":            { light: "d3b1b80fc_generated_image.png", dark: "3eef73761_generated_image.png" },
  "Decline Crunch":           { light: "bd6d47609_generated_image.png", dark: "463c007fd_generated_image.png" },
  "Hanging Leg Raise":        { light: "f2bcfd3f9_generated_image.png", dark: "b0157850e_generated_image.png" },
  "Ab Rollout":               { light: "93e324175_generated_image.png", dark: "44f5ed1ec_generated_image.png" },
  "Side Plank":               { light: "89eb02f92_generated_image.png", dark: "a65b1e6a6_generated_image.png" },
  "Dead Bug":                 { light: "9143f1e83_generated_image.png", dark: "e4b63961d_generated_image.png" },
  "Toes to Bar":              { light: "97be9af2b_generated_image.png", dark: "660c4cedd_generated_image.png" },
  "Pallof Press":             { light: "b70e1da4e_generated_image.png", dark: "4a0a8d06d_generated_image.png" },
  "Hollow Body Hold":         { light: "cfa5a2e01_generated_image.png", dark: "82f042068_generated_image.png" },
  "Dragon Flag":              { light: "c648540f6_generated_image.png", dark: "874bde82d_generated_image.png" },
  "Cable Kickback":           { light: "b33aaf13b_generated_image.png", dark: "6eadb182d_generated_image.png" },
  "Glute Bridge":             { light: "0bb529857_generated_image.png", dark: "accdab0d0_generated_image.png" },
  "Single Leg Hip Thrust":    { light: "d3c24bdb9_generated_image.png", dark: "e64fd21b2_generated_image.png" },
  "Cable Pull Through":       { light: "4558b12f3_generated_image.png", dark: "c7edef34a_generated_image.png" },
  "Standing Calf Raise":      { light: "d8da58053_generated_image.png", dark: "65427fda1_generated_image.png" },
  "Seated Calf Raise":        { light: "728cb200b_generated_image.png", dark: "bce36b788_generated_image.png" },
  "Donkey Calf Raise":        { light: "91f4d8092_generated_image.png", dark: "b15180536_generated_image.png" },
  "Leg Press Calf Raise":     { light: "2ea642eb3_generated_image.png", dark: "0a728cece_generated_image.png" },
  "Farmer Carry":             { light: "cc62420bd_generated_image.png", dark: "12016ac25_generated_image.png" },
  "Reverse Curl":             { light: "17b9b21c2_generated_image.png", dark: "317be8d51_generated_image.png" },
  "Kettlebell Swing":         { light: "62033fb71_generated_image.png", dark: "eff4089b3_generated_image.png" },
  "Box Jump":                 { light: "adca0047d_generated_image.png", dark: "761f2e375_generated_image.png" },
  "Burpees":                  { light: "f290c0951_generated_image.png", dark: "4b75efb62_generated_image.png" },
  "Power Clean":              { light: "55fbe5f52_generated_image.png", dark: "9cfd228c9_generated_image.png" },
  "Nordic Hamstring Curl":    { light: "1e83d0f7f_generated_image.png", dark: "3abbff058_generated_image.png" },
  "Sissy Squat":              { light: "2e30672b8_generated_image.png", dark: "e699e986d_generated_image.png" },
  "Meadows Row":              { light: "275d75415_generated_image.png", dark: "5044e3e1b_generated_image.png" },
  "Wrist Curl":               { light: "6f04347d3_generated_image.png", dark: "cdf8b536a_generated_image.png" },
  "Single Leg Calf Raise":    { light: "a4e06cc73_generated_image.png", dark: "333691206_generated_image.png" },
};

const NEW_EXERCISES = [
  // BATCH 2
  { name: "Spiderman", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["shoulders", "legs"], instructions: "In a push-up position, bring one knee toward the same-side elbow as you lower. Return and alternate sides." },
  { name: "Spinning", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Pedal on a stationary spin bike at varying intensities and cadences, following intervals or steady state." },
  { name: "Split Jerk", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "From front rack, dip and drive the bar overhead while splitting feet into a lunge position. Recover to standing." },
  { name: "Split Squat (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold dumbbells with one foot forward. Lower back knee toward floor, then drive through front foot to stand." },
  { name: "Sprints", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Run at maximum effort for a short distance or time, then rest and repeat." },
  { name: "Squat (Band)", muscle_group: "legs", equipment: "bands", secondary_muscles: ["glutes"], instructions: "Stand on a resistance band holding handles at shoulders. Squat down, then stand against the band resistance." },
  { name: "Squat (Bodyweight)", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand with feet shoulder-width. Squat down until thighs are at least parallel, then drive back up." },
  { name: "Squat (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold dumbbells at shoulders or sides. Squat down until thighs are parallel, then stand back up." },
  { name: "Squat (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Position yourself in a squat machine. Lower into a squat position, then drive back up against the resistance." },
  { name: "Squat (Smith Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Stand under Smith machine bar on upper back. Unrack and squat down, then drive back up." },
  { name: "Squat (Suspension)", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Hold TRX straps and lean back slightly. Squat down using the straps for balance, then stand." },
  { name: "Squat Row", muscle_group: "legs", equipment: "cable", secondary_muscles: ["back"], instructions: "Hold a cable handle, squat down, then stand while simultaneously rowing the handle to your torso." },
  { name: "Stair Machine (Floors)", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Climb the stair machine continuously, tracking progress by floors climbed." },
  { name: "Stair Machine (Steps)", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Climb the stair machine continuously, tracking progress by individual steps." },
  { name: "Standing Cable Glute Kickbacks", muscle_group: "glutes", equipment: "cable", secondary_muscles: [], instructions: "Attach cable to ankle, face the machine. Kick leg straight back against resistance, squeezing glute." },
  { name: "Standing Calf Raise (Barbell)", muscle_group: "calves", equipment: "barbell", secondary_muscles: [], instructions: "Hold barbell on upper back. Rise up onto toes as high as possible, then lower heels below the platform." },
  { name: "Standing Calf Raise (Dumbbell)", muscle_group: "calves", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbells at sides standing on a platform edge. Rise onto toes, then lower heels for a stretch." },
  { name: "Standing Calf Raise (Smith)", muscle_group: "calves", equipment: "machine", secondary_muscles: [], instructions: "Stand under Smith machine bar on a platform. Rise onto toes, then lower heels below platform level." },
  { name: "Standing Leg Curls", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Stand at a leg curl machine with pad behind ankle. Curl heel toward glute, then lower slowly." },
  { name: "Standing Military Press (Barbell)", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["triceps", "core"], instructions: "Hold barbell at shoulder height while standing. Press it overhead until arms lock out, then lower." },
  { name: "Sternum Pull Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Perform a pull-up but lean back and pull your sternum to the bar instead of your chin. Lower with control." },
  { name: "Straight Leg Deadlift", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["back", "glutes"], instructions: "Hold barbell with legs nearly straight. Hinge at hips lowering the bar, then drive hips forward to stand." },
  { name: "Stretching", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Perform various static or dynamic stretches targeting major muscle groups to improve flexibility." },
  { name: "Sumo Squat (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes"], instructions: "Hold barbell on back with wide stance and toes out. Squat down keeping knees tracking over toes, then stand." },
  { name: "Sumo Squat (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold a dumbbell between legs with wide stance. Squat down, then drive back up through heels." },
  { name: "Sumo Squat (Kettlebell)", muscle_group: "legs", equipment: "kettlebell", secondary_muscles: ["glutes"], instructions: "Hold kettlebell between legs with wide stance. Squat down keeping chest up, then stand." },
  { name: "Superman", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Lie face down with arms extended. Simultaneously raise arms and legs off the floor, hold briefly, then lower." },
  { name: "Swimming", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: [], instructions: "Swim laps using any stroke (freestyle, backstroke, etc.) for cardiovascular conditioning." },
  { name: "Thruster (Kettlebell)", muscle_group: "legs", equipment: "kettlebell", secondary_muscles: ["shoulders"], instructions: "Hold kettlebells in rack position. Squat down, then drive up and press them overhead in one motion." },
  { name: "Toe Touch", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on back with legs vertical. Crunch up and reach hands toward toes, then lower upper body." },
  { name: "Torso Rotation", muscle_group: "core", equipment: "machine", secondary_muscles: [], instructions: "Sit in torso rotation machine. Rotate against the resistance to one side, then return and repeat or switch sides." },
  { name: "Treadmill", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Walk, jog, or run on a treadmill at your desired speed and incline for cardiovascular training." },
  { name: "Triceps Dip (Assisted)", muscle_group: "triceps", equipment: "machine", secondary_muscles: ["chest"], instructions: "Use assisted dip machine. Lower body by bending elbows, then press back up with machine assistance." },
  { name: "Triceps Dip (Weighted)", muscle_group: "triceps", equipment: "bodyweight", secondary_muscles: ["chest"], instructions: "Perform dips with added weight via belt or dumbbell between feet. Lower until upper arms are parallel, then press up." },
  { name: "Triceps Extension (Barbell)", muscle_group: "triceps", equipment: "barbell", secondary_muscles: [], instructions: "Lie on bench holding barbell overhead. Lower it toward your forehead by bending elbows, then extend." },
  { name: "Triceps Extension (Cable)", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Face a high cable with bar or rope. Push down until arms are straight, keeping elbows at sides." },
  { name: "Triceps Extension (Dumbbell)", muscle_group: "triceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbell overhead. Lower it behind your head by bending elbows, then extend back up." },
  { name: "Triceps Extension (Machine)", muscle_group: "triceps", equipment: "machine", secondary_muscles: [], instructions: "Sit at triceps extension machine. Press handles down until arms are straight, then return slowly." },
  { name: "Triceps Extension (Suspension)", muscle_group: "triceps", equipment: "bodyweight", secondary_muscles: [], instructions: "Hold TRX handles overhead facing away from anchor. Extend arms by pressing forward, then return." },
  { name: "Triceps Kickback (Cable)", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Hinge forward holding cable handle. Extend arm back until straight, squeezing tricep, then return." },
  { name: "Triceps Pressdown", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Stand at high cable with straight bar. Press down until arms are fully extended, then return." },
  { name: "Triceps Pushdown", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Stand at high cable with bar attachment. Push down keeping elbows at sides until arms are straight." },
  { name: "Triceps Rope Pushdown", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Stand at high cable with rope. Push down and spread the rope at the bottom, then return." },
  { name: "Upright Row (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: ["back"], instructions: "Stand at low cable with bar. Pull up along your body until elbows are at shoulder height, then lower." },
  { name: "Upright Row (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["back"], instructions: "Hold dumbbells in front of thighs. Pull up along body until elbows reach shoulder height, then lower." },
  { name: "Vertical Traction Machine", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at vertical traction machine. Pull handles down to chest level, squeezing lats, then return." },
  { name: "Waiter Curl", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold a dumbbell vertically with both hands under the top plate. Curl it up to chest height, then lower." },
  { name: "Walking", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Walk at a steady pace for cardiovascular health and active recovery." },
  { name: "Wall Ball", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Hold medicine ball at chest, squat down, then drive up and throw the ball to a target on the wall. Catch and repeat." },
  { name: "Warm Up", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Perform light cardio and dynamic movements to raise body temperature and prepare for exercise." },
  { name: "Wide Pull Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Grip pull-up bar wider than shoulder width. Pull chin above bar, focusing on lat engagement, then lower." },
  { name: "Wide-Elbow Triceps Press", muscle_group: "triceps", equipment: "barbell", secondary_muscles: ["chest"], instructions: "Lie on bench with barbell. Lower with elbows flared wide toward your chest, then press back up." },
  { name: "Yoga", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Perform a series of yoga poses focusing on flexibility, balance, strength, and breathing." },
  { name: "Zercher Squat", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["core", "back"], instructions: "Hold barbell in the crooks of your elbows. Squat down keeping torso upright, then drive back up." },
  // BATCH 3
  { name: "Reverse Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: ["forearms"], instructions: "Hold dumbbells with an overhand (pronated) grip. Curl them up to shoulder height keeping wrists flat, then lower." },
  { name: "Reverse Grip Concentration Curl", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: ["forearms"], instructions: "Sit on a bench with a dumbbell hanging between your legs using an overhand grip. Curl it up, then lower slowly." },
  { name: "Rope Cable Curl", muscle_group: "biceps", equipment: "cable", secondary_muscles: ["forearms"], instructions: "Attach a rope to a low cable. Curl the rope up with a neutral grip, spreading the ends apart at the top for peak contraction." },
  { name: "Spider Curl (Barbell)", muscle_group: "biceps", equipment: "barbell", secondary_muscles: [], instructions: "Lie face down on an incline bench. Let the barbell hang, then curl it up against the bench, keeping upper arms vertical." },
  { name: "Spider Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Lie face down on an incline bench. Let dumbbells hang, then curl them up against the bench, keeping upper arms vertical." },
  { name: "Single Arm Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: [], instructions: "Stand facing a low cable. Curl the single handle up to shoulder height with a supinated grip, then lower slowly." },
  { name: "Seated Incline Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Sit on an incline bench holding dumbbells. Let them hang straight down, then curl up, keeping your upper arms back." },
  { name: "Reverse Fly Single Arm (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: ["back"], instructions: "Stand sideways to a cable set at face height. Pull the handle across your body and out to the side, squeezing the rear delt." },
  { name: "Shoulder Press (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Sit or stand holding dumbbells at shoulder height. Press them straight overhead until arms are extended, then lower." },
  { name: "Shoulder Press (Machine Plates)", muscle_group: "shoulders", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Sit at a plate-loaded shoulder press machine. Press the handles overhead until arms are extended, then lower slowly." },
  { name: "Shoulder Taps", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Start in a push-up position. Lift one hand and tap the opposite shoulder, then alternate while keeping hips stable." },
  { name: "Single Arm Landmine Press (Barbell)", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["triceps", "core"], instructions: "Hold the end of a landmine barbell at shoulder height in one hand. Press it up and forward at an angle, then lower." },
  { name: "Single Arm Lateral Raise (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: [], instructions: "Stand sideways to a low cable. Raise the handle out to the side to shoulder height with a slight elbow bend, then lower." },
  { name: "Seated Lateral Raise (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: [], instructions: "Sit on a bench holding dumbbells at your sides. Raise them out to shoulder height, then lower slowly." },
  { name: "Seated Overhead Press (Barbell)", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["triceps"], instructions: "Sit on a bench holding a barbell at shoulder height. Press it overhead until arms are extended, then lower." },
  { name: "Seated Overhead Press (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Sit on a bench holding dumbbells at shoulder height. Press them overhead until arms are extended, then lower." },
  { name: "Seated Shoulder Press (Machine)", muscle_group: "shoulders", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Sit at a shoulder press machine. Press the handles overhead until arms are extended, then lower slowly." },
  { name: "Reverse Grip Lat Pulldown (Cable)", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a lat pulldown machine with a supinated (underhand) grip. Pull the bar to your upper chest, squeezing the lats, then return." },
  { name: "Rope Straight Arm Pulldown", muscle_group: "back", equipment: "cable", secondary_muscles: ["chest"], instructions: "Stand facing a high cable with a rope. Keep arms straight and pull the rope down to your thighs in an arc, squeezing the lats." },
  { name: "Scapular Pull Ups", muscle_group: "back", equipment: "bodyweight", secondary_muscles: [], instructions: "Hang from a pull-up bar with arms straight. Without bending the elbows, depress and retract your shoulder blades to raise your body slightly." },
  { name: "Seated Cable Row - Bar Grip", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a cable row station with a straight bar. Pull it to your lower chest with elbows close to your sides, then return." },
  { name: "Seated Cable Row - Bar Wide Grip", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a cable row station with a wide bar. Pull it to your lower chest with elbows flared out, squeezing the upper back, then return." },
  { name: "Seated Cable Row - V Grip", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a cable row station with a V-bar attachment. Pull it to your lower chest with elbows tucked in, then return." },
  { name: "Single Arm Cable Row", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit or stand at a cable station. Pull a single handle to your hip with one arm, rotating slightly, then return." },
  { name: "Single Arm Lat Pulldown", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a lat pulldown with a single handle. Pull it down to shoulder height with one arm, squeezing the lat, then return." },
  { name: "Seated Row (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at a seated row machine. Grip the handles and pull them toward your torso, squeezing the back, then slowly return." },
  { name: "Single Arm Cable Crossover", muscle_group: "chest", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Stand sideways to a high cable. Pull the handle across your body in a fly motion, squeezing the chest, then return." },
  { name: "Seated Chest Flys (Cable)", muscle_group: "chest", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Sit between two low cables. With arms slightly bent, bring the handles together in front of your chest in a wide arc, then return." },
  { name: "Ring Push Up", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps", "core"], instructions: "Hold gymnastics rings with arms extended below your chest. Lower your chest toward the rings, then push back up." },
  { name: "Ring Dips", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps", "shoulders"], instructions: "Support yourself on gymnastics rings. Lower your body by bending the elbows, leaning slightly forward, then press back up." },
  { name: "Single Arm Tricep Extension (Dumbbell)", muscle_group: "triceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold one dumbbell overhead with one arm. Lower it behind your head by bending the elbow, then extend back up." },
  { name: "Single Arm Triceps Pushdown (Cable)", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Hold a single cable handle at a high pulley. Push it down with one arm until fully extended, keeping the elbow at your side, then return." },
  { name: "Seated Dip Machine", muscle_group: "triceps", equipment: "machine", secondary_muscles: ["chest"], instructions: "Sit at a dip machine. Grip the handles and press them down, extending your arms fully, then slowly return." },
  { name: "Seated Triceps Press", muscle_group: "triceps", equipment: "machine", secondary_muscles: [], instructions: "Sit at a triceps press machine. Grip the handles and press forward or downward until arms are extended, then slowly return." },
  { name: "Reverse Plank", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["glutes", "back"], instructions: "Sit with legs extended and hands behind you. Lift your hips until your body forms a straight line from head to heels, then hold." },
  { name: "Russian Twist (Bodyweight)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Sit with knees bent and feet lifted. Rotate your torso from side to side, touching the floor on each side." },
  { name: "Russian Twist (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Sit with knees bent and feet lifted, holding a weight plate or medicine ball. Rotate your torso from side to side." },
  { name: "Sit Up", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with knees bent and feet anchored. Curl your torso all the way up to your knees, then lower back down." },
  { name: "Sit Up (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back holding a weight plate to your chest. Curl your torso all the way up to your knees, then lower back down." },
  { name: "Side Bend", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Stand upright. Bend your torso to one side as far as possible, hold briefly, then return to center and repeat on the other side." },
  { name: "Side Bend (Dumbbell)", muscle_group: "core", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold a dumbbell in one hand at your side. Bend your torso toward the opposite side, then return to center." },
  { name: "Single Leg Glute Bridge", muscle_group: "glutes", equipment: "bodyweight", secondary_muscles: ["legs"], instructions: "Lie on your back with one knee bent. Extend the other leg straight. Drive the bent-knee foot into the floor to lift your hips, then lower." },
  { name: "Single Leg Hip Thrust (Dumbbell)", muscle_group: "glutes", equipment: "dumbbell", secondary_muscles: ["legs"], instructions: "Set up for a hip thrust with a dumbbell on one hip. Extend the other leg. Drive hips up until your body is straight, then lower." },
  { name: "Reverse Lunge", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand upright. Step one foot back and lower your back knee toward the floor, then push back up to standing." },
  { name: "Reverse Lunge (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes"], instructions: "Hold a barbell on your upper back. Step one foot back and lower your back knee toward the floor, then push back up." },
  { name: "Reverse Lunge (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold dumbbells at your sides. Step one foot back and lower your back knee toward the floor, then push back up." },
  { name: "Single Leg Extensions", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Sit at a leg extension machine. Place one foot under the pad and extend that leg fully, then lower slowly." },
  { name: "Single Leg Press (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Sit in a leg press machine with one foot centered on the platform. Press it away until the leg is extended, then lower slowly." },
  { name: "Single Leg Romanian Deadlift (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes", "core"], instructions: "Hold a barbell and balance on one leg. Hinge forward, letting the bar lower toward the floor while the free leg extends behind you." },
  { name: "Single Leg Romanian Deadlift (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes", "core"], instructions: "Hold dumbbells and balance on one leg. Hinge forward, letting the dumbbells lower toward the floor while the free leg extends behind you." },
  { name: "Sissy Squat (Weighted)", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Hold a weight plate against your chest. Lean back and drop your knees toward the floor in a sissy squat motion, then return." },
  { name: "Romanian Deadlift (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes", "back"], instructions: "Hold a barbell with an overhand grip. Hinge at the hips, sliding the bar down your thighs, then drive hips forward to stand." },
  { name: "Romanian Deadlift (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes", "back"], instructions: "Hold dumbbells in front of your thighs. Hinge at the hips, letting dumbbells slide down your legs, then drive hips forward to stand." },
  { name: "Single Leg Standing Calf Raise", muscle_group: "calves", equipment: "bodyweight", secondary_muscles: [], instructions: "Stand on one foot on the edge of a step. Rise up onto your toes as high as possible, then lower slowly below the step level." },
  { name: "Single Leg Standing Calf Raise (Barbell)", muscle_group: "calves", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell across your upper back and balance on one foot. Rise up onto your toes, then lower slowly." },
  { name: "Single Leg Standing Calf Raise (Dumbbell)", muscle_group: "calves", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold a dumbbell and balance on one foot on a step. Rise up onto your toes, then lower slowly below the step." },
  { name: "Single Leg Standing Calf Raise (Machine)", muscle_group: "calves", equipment: "machine", secondary_muscles: [], instructions: "Use a calf raise machine with one leg. Rise up onto your toes as high as possible, then lower slowly." },
  { name: "Shrug (Barbell)", muscle_group: "back", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell in front of you. Shrug your shoulders straight up toward your ears as high as possible, hold briefly, then lower." },
  { name: "Shrug (Cable)", muscle_group: "back", equipment: "cable", secondary_muscles: [], instructions: "Stand at a low cable holding a bar. Shrug your shoulders straight up, hold briefly, then lower." },
  { name: "Shrug (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbells at your sides. Shrug your shoulders straight up toward your ears, hold briefly, then lower." },
  { name: "Shrug (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: [], instructions: "Stand in a shrug machine with handles at your sides. Shrug your shoulders straight up, hold briefly, then lower." },
  { name: "Shrug (Smith Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: [], instructions: "Stand inside a Smith machine with the bar at thigh height. Shrug your shoulders up as high as possible, hold briefly, then lower." },
  { name: "Seated Palms Up Wrist Curl", muscle_group: "forearms", equipment: "barbell", secondary_muscles: [], instructions: "Sit on a bench with forearms resting on thighs, palms up holding a barbell. Curl your wrists upward, then lower slowly." },
  { name: "Seated Wrist Extension (Barbell)", muscle_group: "forearms", equipment: "barbell", secondary_muscles: [], instructions: "Sit on a bench with forearms resting on thighs, palms down holding a barbell. Extend your wrists upward, then lower slowly." },
  { name: "Rowing Machine", muscle_group: "back", equipment: "machine", secondary_muscles: ["legs"], instructions: "Sit on a rowing machine. Drive with your legs, lean back, and pull the handle to your chest. Reverse the motion to return." },
  { name: "Running", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Run at a comfortable or challenging pace outdoors or on a treadmill for your target duration or distance." },
  { name: "Skiing", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Ski down slopes using proper technique, controlling speed and direction through carving and turning." },
  { name: "Snowboarding", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Ride a snowboard down slopes, using edge control and body movement to steer and control speed." },
  { name: "Skating", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Skate on ice or inline skates, pushing off with each leg in a side-to-side motion." },
  { name: "Snatch", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "From the floor, explosively pull the barbell overhead in one motion, catching it with arms locked out overhead." },
  { name: "Ring Pull Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Hang from gymnastics rings with a neutral grip. Pull your chest up to the rings, then lower slowly." },
  // BATCH 4
  { name: "Lateral Box Jump", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand beside a box. Jump laterally onto it with both feet, land softly, then step or jump back down and repeat." },
  { name: "Lateral Lunge", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand upright. Step one foot out to the side and lower into a side lunge, pushing your hips back, then return to standing." },
  { name: "Lateral Squat", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand with feet wide. Shift your weight to one side, bending that knee into a squat while keeping the other leg straight, then return." },
  { name: "Leg Extension (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Sit at a leg extension machine with the pad on your ankles. Extend both legs until straight, then lower slowly." },
  { name: "Leg Press (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Sit in a leg press machine with feet shoulder-width on the platform. Press the weight away until legs are nearly extended, then lower slowly." },
  { name: "Leg Press Horizontal (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Lie in a horizontal leg press machine. Push the platform away until legs are extended, then lower slowly." },
  { name: "Lunge", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand upright. Step one foot forward and lower your back knee toward the floor, then push back to standing. Alternate legs." },
  { name: "Lunge (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes"], instructions: "Hold a barbell on your upper back. Step forward into a lunge, lower your back knee, then push back up." },
  { name: "Lunge (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold dumbbells at your sides. Step forward into a lunge, lower your back knee, then push back up and alternate." },
  { name: "Lying Leg Curl (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Lie face down on a leg curl machine with the pad behind your ankles. Curl your legs up toward your glutes, then lower slowly." },
  { name: "Overhead Dumbbell Lunge", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["shoulders", "core"], instructions: "Hold dumbbells overhead with arms extended. Step forward into a lunge, maintaining upright torso and arms overhead throughout." },
  { name: "Overhead Squat", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["shoulders", "core"], instructions: "Hold a barbell overhead with a wide grip and arms locked. Squat deep keeping the bar over your midfoot, then drive back up." },
  { name: "Pause Squat (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes", "core"], instructions: "Squat down with a barbell and pause for 2-3 seconds at the bottom, then explosively drive back up." },
  { name: "Pendulum Squat (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Stand in a pendulum squat machine with shoulders under the pads. Lower into a deep squat, then drive back up." },
  { name: "Lateral Leg Raises", muscle_group: "glutes", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your side with legs straight. Raise the top leg as high as possible, then lower slowly." },
  { name: "Partial Glute Bridge (Barbell)", muscle_group: "glutes", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Lie on your back with a barbell across your hips. Drive hips up to a partial range, squeezing glutes, then lower." },
  { name: "Rear Kick (Machine)", muscle_group: "glutes", equipment: "machine", secondary_muscles: [], instructions: "Position yourself in a glute kickback machine. Kick one leg back and up against the resistance, squeezing the glute at the top." },
  { name: "Leg Raise Parallel Bars", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Support yourself on parallel bars with arms straight. Raise your legs straight out in front to parallel, then lower slowly." },
  { name: "Lying Knee Raise", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie flat on your back. Bring both knees toward your chest, then lower them back down without touching the floor." },
  { name: "Lying Leg Raise", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie flat on your back with legs straight. Raise both legs to 90 degrees, then slowly lower without touching the floor." },
  { name: "Oblique Crunch", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with knees bent. Crunch up and rotate, bringing one elbow toward the opposite knee, then alternate." },
  { name: "Plank Pushup", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["chest", "triceps"], instructions: "Start in a forearm plank. Push up one arm at a time to a full push-up position, then lower back down. Alternate the leading arm." },
  { name: "Lateral Raise (Band)", muscle_group: "shoulders", equipment: "bands", secondary_muscles: [], instructions: "Stand on a resistance band and hold the ends. Raise both arms out to the sides to shoulder height, then lower slowly." },
  { name: "Lateral Raise (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: [], instructions: "Stand beside a low cable. Raise the handle out to the side to shoulder height with a slight elbow bend, then lower." },
  { name: "Lateral Raise (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbells at your sides. Raise them out to shoulder height with a slight bend in the elbows, then lower slowly." },
  { name: "Lateral Raise (Machine)", muscle_group: "shoulders", equipment: "machine", secondary_muscles: [], instructions: "Sit at a lateral raise machine. Place your arms under the pads and raise them to shoulder height, then lower slowly." },
  { name: "Overhead Plate Raise", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: [], instructions: "Hold a weight plate with both hands. Raise it straight overhead from in front of your waist, then lower back down." },
  { name: "Overhead Press (Barbell)", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["triceps"], instructions: "Stand holding a barbell at shoulder height. Press it straight overhead until arms are locked out, then lower." },
  { name: "Overhead Press (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Stand or sit holding dumbbells at shoulder height. Press them overhead until arms are extended, then lower." },
  { name: "Overhead Press (Smith Machine)", muscle_group: "shoulders", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Sit under a Smith machine bar at shoulder height. Press it overhead until arms are locked out, then lower." },
  { name: "Push Press", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs", "triceps"], instructions: "Hold a barbell at shoulder height. Dip slightly at the knees, then explosively drive it overhead using leg momentum." },
  { name: "Rear Delt Reverse Fly (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: ["back"], instructions: "Set two cables at face height, crossed. Pull handles apart in a reverse fly motion, squeezing rear delts." },
  { name: "Rear Delt Reverse Fly (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["back"], instructions: "Hinge forward holding dumbbells. Raise them out to the sides with a slight elbow bend, squeezing the rear delts." },
  { name: "Rear Delt Reverse Fly (Machine)", muscle_group: "shoulders", equipment: "machine", secondary_muscles: ["back"], instructions: "Sit at a reverse fly machine facing the pad. Pull the handles back and out in a wide arc, squeezing the rear delts." },
  { name: "Low Cable Fly Crossovers", muscle_group: "chest", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Set cables to the lowest position. Pull both handles up and together in a wide arc, focusing on the upper chest." },
  { name: "Low Row (Suspension)", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Hold TRX straps and lean back with body straight. Pull your chest to the handles, keeping elbows low, then extend back." },
  { name: "Meadows Rows (Barbell)", muscle_group: "back", equipment: "barbell", secondary_muscles: ["biceps"], instructions: "Stand perpendicular to a landmine barbell. Row the end of the bar up to your hip with one hand, elbow flaring out, then lower." },
  { name: "Negative Pull Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Start at the top of a pull-up position. Lower yourself as slowly as possible — taking 5-10 seconds — until arms are fully extended." },
  { name: "Pendlay Row (Barbell)", muscle_group: "back", equipment: "barbell", secondary_muscles: ["biceps", "core"], instructions: "Bar on the floor, hinge to parallel. Explosively row it to your lower chest, then lower it fully to the floor each rep." },
  { name: "Pullover (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["chest", "triceps"], instructions: "Lie perpendicular on a bench. Hold a dumbbell with both hands above your chest. Lower it behind your head, then pull back over." },
  { name: "Pullover (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["chest"], instructions: "Sit at a pullover machine with arms over the pads. Pull the pads down in an arc toward your hips, then slowly return." },
  { name: "Renegade Row (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["core", "biceps"], instructions: "Start in a push-up position holding dumbbells. Row one dumbbell to your hip while balancing, then switch sides." },
  { name: "Overhead Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: [], instructions: "Set two cables at head height. Hold the handles with arms extended outward. Curl your hands toward your head, squeezing the biceps." },
  { name: "Pinwheel Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: ["forearms"], instructions: "Hold dumbbells with a neutral grip. Curl one across your body to the opposite shoulder, then alternate in a pinwheel motion." },
  { name: "Plate Curl", muscle_group: "biceps", equipment: "bodyweight", secondary_muscles: ["forearms"], instructions: "Hold a weight plate on its sides with both hands. Curl it up to shoulder height, then lower." },
  { name: "Preacher Curl (Barbell)", muscle_group: "biceps", equipment: "barbell", secondary_muscles: [], instructions: "Sit at a preacher bench with a barbell. Curl the bar up to shoulder height, then slowly lower all the way down." },
  { name: "Preacher Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Sit at a preacher bench with a dumbbell. Curl it up to shoulder height, then slowly lower all the way down." },
  { name: "Preacher Curl (Machine)", muscle_group: "biceps", equipment: "machine", secondary_muscles: [], instructions: "Sit at a preacher curl machine with upper arms on the pad. Curl the handles up, then lower slowly." },
  { name: "Reverse Curl (Barbell)", muscle_group: "biceps", equipment: "barbell", secondary_muscles: ["forearms"], instructions: "Hold a barbell with an overhand (pronated) grip. Curl it up to shoulder height keeping wrists flat, then lower." },
  { name: "Reverse Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: ["forearms"], instructions: "Stand at a low cable with a straight bar using an overhand grip. Curl the bar up to shoulder height, then lower." },
  { name: "Overhead Triceps Extension (Cable)", muscle_group: "triceps", equipment: "cable", secondary_muscles: [], instructions: "Face away from a high cable with a rope behind your head. Extend arms forward and up until fully straight, then return." },
  { name: "One Arm Push Up", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps", "core"], instructions: "Start in a push-up position with one hand behind your back. Lower your chest to the floor with one arm, then push back up." },
  { name: "Plate Press", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Lie on a bench holding a weight plate above your chest with both hands on the edges. Press it up, then lower slowly." },
  { name: "Plate Squeeze (Svend Press)", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Hold two plates squeezed together at chest height. Press them forward while continuing to squeeze, then return." },
  { name: "Push Up - Close Grip", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Place hands close together under your chest. Lower your chest toward your hands, then push back up." },
  { name: "Push Up (Weighted)", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Place a weight plate on your upper back. Perform a push-up, lowering your chest to the floor, then pressing back up." },
  { name: "Lying Neck Curls", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back on a bench with your head hanging off. Curl your chin toward your chest, then lower slowly." },
  { name: "Lying Neck Curls (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with a small plate held on your forehead. Curl your chin toward your chest against the resistance, then lower." },
  { name: "Lying Neck Extension", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie face down on a bench with your head hanging off. Extend your head back as far as comfortable, then lower." },
  { name: "Lying Neck Extension (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie face down with a small plate on the back of your head. Extend your head back against the resistance, then lower." },
  { name: "Press Under", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Hold a barbell overhead. Lower into a squat and press the bar up simultaneously, then stand back up." },
  { name: "Power Snatch", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "From a hang or floor position, explosively pull the barbell overhead in one motion, catching with a slight squat." },
  { name: "Pilates", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Perform a series of controlled Pilates movements focusing on core strength, posture, and flexibility." },
  { name: "Pull Up (Assisted)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Use an assisted pull-up machine. Grip the bar and pull your chin above it with the machine reducing your effective weight." },
  { name: "Pull Up (Band)", muscle_group: "back", equipment: "bands", secondary_muscles: ["biceps"], instructions: "Loop a resistance band over a pull-up bar and place your foot or knee in it. Pull your chin above the bar with band assistance." },
  { name: "Pull Up (Weighted)", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Attach extra weight via a belt or hold a dumbbell between your feet. Perform a full pull-up with the added resistance." },
  // BATCH 5
  { name: "Front Raise (Band)", muscle_group: "shoulders", equipment: "bands", secondary_muscles: [], instructions: "Stand on a resistance band and hold the ends. Raise both arms straight in front of you to shoulder height, then lower." },
  { name: "Front Raise (Barbell)", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell with an overhand grip at thigh level. Raise it straight in front of you to shoulder height, then lower." },
  { name: "Front Raise (Cable)", muscle_group: "shoulders", equipment: "cable", secondary_muscles: [], instructions: "Stand facing away from a low cable. Raise the handle straight in front of you to shoulder height, then lower." },
  { name: "Front Raise (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbells in front of your thighs. Raise them straight forward to shoulder height, then lower slowly." },
  { name: "Front Raise (Suspension)", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Hold TRX straps facing the anchor. Lean back slightly and raise your arms straight forward to shoulder height, then return." },
  { name: "Full Squat", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Stand with feet shoulder-width apart. Lower into a full deep squat until your hips pass below your knees, then drive back up." },
  { name: "Good Morning (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["back", "glutes"], instructions: "Place a barbell on your upper back. Hinge forward at the hips with a slight knee bend until your torso is near parallel, then return." },
  { name: "Hack Squat (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Stand in a hack squat machine with shoulders under the pads. Lower into a deep squat, then drive the platform back up." },
  { name: "Incline Push Ups", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Place hands on an elevated surface like a bench. Perform a push-up, lowering your chest to the surface, then push back up." },
  { name: "Jumping Lunge", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "From a lunge position, explosively jump and switch legs in the air, landing in the opposite lunge. Alternate continuously." },
  { name: "Jump Squat", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Squat down, then explode upward jumping as high as possible. Land softly and immediately go into the next squat." },
  { name: "Glute Ham Raise", muscle_group: "legs", equipment: "machine", secondary_muscles: ["back"], instructions: "Anchor your feet in a GHR machine. Lower your torso toward the floor using your hamstrings, then pull back up." },
  { name: "Glute Kickback on Floor", muscle_group: "glutes", equipment: "bodyweight", secondary_muscles: [], instructions: "On all fours, kick one leg back and up with knee bent 90 degrees, squeezing the glute at the top, then lower." },
  { name: "Hip Thrust (Barbell)", muscle_group: "glutes", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Sit against a bench with a barbell across your hips. Drive your hips up until your body forms a straight line, squeezing glutes at the top." },
  { name: "Hip Thrust (Machine)", muscle_group: "glutes", equipment: "machine", secondary_muscles: ["legs"], instructions: "Sit in a hip thrust machine with the pad across your hips. Drive your hips forward against the resistance, then return." },
  { name: "Hip Thrust (Smith Machine)", muscle_group: "glutes", equipment: "machine", secondary_muscles: ["legs"], instructions: "Sit against a bench with a Smith machine bar across your hips. Drive your hips up until straight, squeezing glutes at top." },
  { name: "Hip Adduction (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Sit in a hip adduction machine with pads on the inside of your knees. Squeeze your knees together against the resistance, then slowly return." },
  { name: "Hip Abduction (Machine)", muscle_group: "glutes", equipment: "machine", secondary_muscles: [], instructions: "Sit in a hip abduction machine with pads on the outside of your knees. Push knees outward against resistance, then slowly return." },
  { name: "Hanging Knee Raise", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Hang from a pull-up bar. Bring your knees up toward your chest, then lower them back down with control." },
  { name: "Heel Taps", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with knees bent and feet flat. Crunch to one side and tap your heel, then alternate sides continuously." },
  { name: "Hollow Rock", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back and press your lower back into the floor. Lift arms, legs, and shoulders slightly and rock back and forth." },
  { name: "Jack Knife (Suspension)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Place feet in TRX straps in a push-up position. Pull your knees toward your chest by flexing at the hips, then extend back out." },
  { name: "Jackknife Sit Up", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie flat with arms extended overhead. Simultaneously raise your legs and torso, reaching hands toward feet at the top." },
  { name: "Knee Raise Parallel Bars", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Support yourself on parallel bars. Raise your knees up toward your chest, then lower with control." },
  { name: "L-Sit Hold", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Support yourself on parallel bars or the floor. Lift your legs parallel to the ground and hold the L-position for time." },
  { name: "Hex Press (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Lie on a bench holding two dumbbells pressed together above your chest. Lower them together keeping them in contact, then press back up." },
  { name: "Incline Bench Press (Smith Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps", "shoulders"], instructions: "Set a bench to incline inside a Smith machine. Unrack the bar, lower to your upper chest, then press back up." },
  { name: "Incline Chest Fly (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["shoulders"], instructions: "Lie on an incline bench holding dumbbells above your chest. Lower them out to the sides in a wide arc, then bring back up." },
  { name: "Incline Chest Press (Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps", "shoulders"], instructions: "Sit at an incline chest press machine. Press the handles forward and up until arms are extended, then lower slowly." },
  { name: "Iso-Lateral Chest Press (Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Sit at an iso-lateral chest press machine. Press each handle independently or together until arms are extended, then return." },
  { name: "Gorilla Row (Kettlebell)", muscle_group: "back", equipment: "kettlebell", secondary_muscles: ["biceps", "core"], instructions: "Stand with feet wide over two kettlebells. Hinge forward and alternate rowing each kettlebell to your hip while balancing on the other." },
  { name: "Iso-Lateral High Row (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at an iso-lateral high row machine. Pull each handle down and back independently or together, squeezing the lats." },
  { name: "Iso-Lateral Low Row", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at an iso-lateral low row machine. Pull each handle toward your torso independently or together, squeezing the back." },
  { name: "Iso-Lateral Row (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at an iso-lateral row machine. Pull the handles toward you one at a time or together, squeezing the back muscles." },
  { name: "Kneeling Pulldown (Band)", muscle_group: "back", equipment: "bands", secondary_muscles: ["biceps"], instructions: "Kneel facing a resistance band anchored above. Pull the band down toward your chest, squeezing the lats, then return." },
  { name: "Kipping Pull Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Hang from a bar. Use a hip kip to generate momentum, then pull your chin above the bar, and repeat in a fluid swinging motion." },
  { name: "Landmine Row", muscle_group: "back", equipment: "barbell", secondary_muscles: ["biceps"], instructions: "Stand over a landmine barbell. Row the end of the bar up to your hip with both or one hand, then lower." },
  { name: "Lat Pulldown - Close Grip (Cable)", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Use a close-grip attachment on a lat pulldown machine. Pull it to your upper chest with elbows close to your sides." },
  { name: "Lat Pulldown (Band)", muscle_group: "back", equipment: "bands", secondary_muscles: ["biceps"], instructions: "Anchor a resistance band overhead. Pull it down toward your chest, squeezing the lats, then slowly return." },
  { name: "Lat Pulldown (Cable)", muscle_group: "back", equipment: "cable", secondary_muscles: ["biceps"], instructions: "Sit at a cable lat pulldown with a wide bar. Pull it to your upper chest, squeezing the lats, then slowly return." },
  { name: "Lat Pulldown (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Sit at a lat pulldown machine. Pull the handles or bar down to your upper chest, squeezing the lats, then return." },
  { name: "Hammer Curl (Band)", muscle_group: "biceps", equipment: "bands", secondary_muscles: ["forearms"], instructions: "Stand on a resistance band with a neutral grip. Curl both handles up to shoulder height maintaining neutral wrists, then lower." },
  { name: "Hammer Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: ["forearms"], instructions: "Attach a rope to a low cable. Curl with a neutral grip to shoulder height, then lower." },
  { name: "Hammer Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: ["forearms"], instructions: "Hold dumbbells with a neutral grip. Curl them up to shoulder height keeping wrists neutral throughout, then lower." },
  { name: "Kettlebell Curl", muscle_group: "biceps", equipment: "kettlebell", secondary_muscles: ["forearms"], instructions: "Hold a kettlebell with both hands or one. Curl it up to shoulder height, then lower slowly." },
  { name: "Handstand Hold", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Kick up into a handstand against a wall. Hold the position with arms straight and body aligned, for time." },
  { name: "Hang Clean", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Start with the bar at hip height. Explosively pull it to shoulder height using hip drive, catching in a front rack position." },
  { name: "Hang Snatch", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Start with the bar at hip height. Explosively pull it overhead in one motion, catching with arms locked out." },
  { name: "High Knee Skips", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Skip forward or in place, driving your knees as high as possible with each skip. Pump your arms in sync." },
  { name: "High Knees", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Run in place, driving your knees up to hip height with each step as fast as possible." },
  { name: "Jump Shrug", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Hold a barbell at thigh height. Drive through your heels and shrug explosively while extending onto your toes." },
  { name: "Jumping Jack", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Stand with feet together and arms at sides. Jump feet out wide while raising arms overhead, then return to start." },
  { name: "Kettlebell Around the World", muscle_group: "shoulders", equipment: "kettlebell", secondary_muscles: ["core"], instructions: "Hold a kettlebell at waist height. Pass it around your body in a circle, alternating hands at the front and back." },
  { name: "Kettlebell Halo", muscle_group: "shoulders", equipment: "kettlebell", secondary_muscles: ["core"], instructions: "Hold a kettlebell upside down at chest height. Circle it around your head in a halo motion, alternating directions." },
  { name: "Kettlebell High Pull", muscle_group: "shoulders", equipment: "kettlebell", secondary_muscles: ["legs"], instructions: "Swing a kettlebell up from between your legs and pull it high to shoulder level with elbow flaring up, then return." },
  { name: "Kettlebell Shoulder Press", muscle_group: "shoulders", equipment: "kettlebell", secondary_muscles: ["triceps", "core"], instructions: "Hold a kettlebell in rack position at shoulder height. Press it straight overhead until arm is locked out, then lower." },
  { name: "Landmine 180", muscle_group: "core", equipment: "barbell", secondary_muscles: ["shoulders"], instructions: "Hold the end of a landmine barbell with both hands. Rotate it in a wide arc from one side to the other, pivoting through your core." },
  { name: "Landmine Squat and Press", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["shoulders"], instructions: "Hold the end of a landmine barbell at shoulder height. Squat down, then as you stand, press it overhead in one motion." },
  { name: "HIIT", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Alternate between periods of maximum effort exercise and brief rest periods. Choose any movements that elevate heart rate." },
  { name: "Hiking", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: [], instructions: "Walk on trails or uneven terrain at a moderate to vigorous pace, navigating elevation changes." },
  { name: "JM Press (Barbell)", muscle_group: "triceps", equipment: "barbell", secondary_muscles: ["chest"], instructions: "Lie on a bench with a barbell. Lower it toward your throat in a press/skull crusher hybrid motion, then press back up." },
  { name: "Kneeling Push Up", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Kneel on the floor with hands shoulder-width. Lower your chest toward the floor, then push back up. Keep a straight line from knees to head." },
  // BATCH 6
  { name: "Burpee Over the Bar", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["chest", "legs"], instructions: "Stand beside a barbell on the floor. Perform a burpee, then jump laterally over the bar. Repeat in the opposite direction." },
  { name: "Butterfly (Pec Deck)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["shoulders"], instructions: "Sit at a pec deck machine. Place your forearms or hands on the pads and bring them together in front of your chest, then return." },
  { name: "Cable Fly Crossovers", muscle_group: "chest", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Stand between two cables set at chest height. Bring the handles together in front of you crossing them, then return." },
  { name: "Chest Dip (Assisted)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Use an assisted dip machine with a forward lean. Lower your body, then press back up with the machine reducing your effective weight." },
  { name: "Chest Dip (Weighted)", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Perform a chest dip leaning slightly forward with added weight via a belt or dumbbell between your legs." },
  { name: "Chest Fly (Band)", muscle_group: "chest", equipment: "bands", secondary_muscles: ["shoulders"], instructions: "Anchor a band behind you at chest height. Hold the ends with arms wide and bring them together in front of your chest." },
  { name: "Chest Fly (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["shoulders"], instructions: "Lie on a flat bench with dumbbells above your chest. Lower them out in a wide arc until you feel a stretch, then bring back up." },
  { name: "Chest Fly (Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["shoulders"], instructions: "Sit at a chest fly machine. Push the handles together in front of your chest, squeezing the pecs, then slowly return." },
  { name: "Chest Fly (Suspension)", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["shoulders", "core"], instructions: "Hold TRX straps with arms wide and lean forward. Bring your hands together in front of your chest, then return." },
  { name: "Chest Press (Band)", muscle_group: "chest", equipment: "bands", secondary_muscles: ["triceps", "shoulders"], instructions: "Anchor a band behind you. Hold the ends at chest height and press forward until arms are extended, then return." },
  { name: "Chest Press (Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps", "shoulders"], instructions: "Sit at a chest press machine. Press the handles forward until arms are extended, then slowly return." },
  { name: "Chest Supported Incline Row (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["biceps"], instructions: "Lie face down on an incline bench. Let the dumbbells hang and row them up to your sides, squeezing your shoulder blades." },
  { name: "Chest Supported Reverse Fly (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["back"], instructions: "Lie face down on an incline bench. With a slight elbow bend, raise the dumbbells out to the sides, squeezing the rear delts." },
  { name: "Chest Supported Y Raise (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["back"], instructions: "Lie face down on an incline bench. Raise the dumbbells diagonally in a Y shape, squeezing the lower traps at the top." },
  { name: "Clap Push Ups", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps"], instructions: "Perform an explosive push-up with enough force to clap your hands together in the air, then land and immediately lower." },
  { name: "Decline Bench Press (Barbell)", muscle_group: "chest", equipment: "barbell", secondary_muscles: ["triceps", "shoulders"], instructions: "Lie on a decline bench with feet anchored. Lower a barbell to your lower chest, then press back up." },
  { name: "Decline Bench Press (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Lie on a decline bench with feet anchored. Lower dumbbells to your lower chest, then press back up." },
  { name: "Decline Bench Press (Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Sit at a decline press machine. Press the handles down and forward until arms are extended, then return." },
  { name: "Decline Bench Press (Smith Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Lie on a decline bench inside a Smith machine. Lower the bar to your lower chest, then press back up." },
  { name: "Decline Chest Fly (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["shoulders"], instructions: "Lie on a decline bench. Lower dumbbells out in a wide arc, focusing on the lower chest, then bring back together." },
  { name: "Decline Push Up", muscle_group: "chest", equipment: "bodyweight", secondary_muscles: ["triceps", "shoulders"], instructions: "Place feet on an elevated surface. Lower your chest toward the floor, then push back up, targeting the upper chest." },
  { name: "Feet Up Bench Press (Barbell)", muscle_group: "chest", equipment: "barbell", secondary_muscles: ["triceps"], instructions: "Lie on a bench with feet up off the floor. Press a barbell from your chest to full extension, keeping your back flat." },
  { name: "Floor Press (Barbell)", muscle_group: "chest", equipment: "barbell", secondary_muscles: ["triceps"], instructions: "Lie on the floor with a barbell above your chest. Lower it until your upper arms touch the floor, then press back up." },
  { name: "Floor Press (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Lie on the floor with dumbbells above your chest. Lower them until upper arms touch the floor, then press back up." },
  { name: "Dead Hang", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["forearms"], instructions: "Hang from a pull-up bar with arms fully extended. Hold the position for time, focusing on shoulder decompression." },
  { name: "Dumbbell Row", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["biceps"], instructions: "Hinge forward holding a dumbbell in each hand. Row both dumbbells up to your hips simultaneously, then lower." },
  { name: "Floor Triceps Dip", muscle_group: "triceps", equipment: "bodyweight", secondary_muscles: [], instructions: "Sit on the floor with hands behind you and knees bent. Bend your elbows to lower your hips toward the floor, then press back up." },
  { name: "Drag Curl", muscle_group: "biceps", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell at thigh level. Drag it up your body by pulling your elbows back, keeping the bar close to your torso throughout." },
  { name: "EZ Bar Biceps Curl", muscle_group: "biceps", equipment: "barbell", secondary_muscles: ["forearms"], instructions: "Hold an EZ bar with an underhand grip. Curl it up to shoulder height, then lower slowly." },
  { name: "Deadlift (Band)", muscle_group: "back", equipment: "bands", secondary_muscles: ["glutes", "legs"], instructions: "Stand on a resistance band and hold the ends. Hinge at the hips and stand up straight, squeezing glutes at the top." },
  { name: "Deadlift (Barbell)", muscle_group: "back", equipment: "barbell", secondary_muscles: ["glutes", "legs"], instructions: "Stand with a barbell over your feet. Hinge down, grip the bar, then drive through your heels to stand up keeping back straight." },
  { name: "Deadlift (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["glutes", "legs"], instructions: "Hold dumbbells in front of your thighs. Hinge at the hips lowering them toward the floor, then drive back up to standing." },
  { name: "Deadlift (Smith Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["glutes", "legs"], instructions: "Stand inside a Smith machine with the bar at mid-shin. Hinge down, grip the bar, and stand up driving through your heels." },
  { name: "Deadlift (Trap bar)", muscle_group: "back", equipment: "barbell", secondary_muscles: ["glutes", "legs"], instructions: "Stand inside a trap bar, grip the handles at your sides. Drive through your heels to stand up keeping back neutral." },
  { name: "Deadlift High Pull", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Start with a barbell on the floor. Drive it up explosively, pulling it to chin height with elbows flaring up at the top." },
  { name: "Frog Pumps (Dumbbell)", muscle_group: "glutes", equipment: "dumbbell", secondary_muscles: ["legs"], instructions: "Lie on your back with soles of feet together and knees out. Place a dumbbell on your hips and pump them up and down." },
  { name: "Cable Core Palloff Press", muscle_group: "core", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Stand sideways to a cable set at chest height. Hold the handle at your chest and press it straight out, resisting rotation, then return." },
  { name: "Cable Twist (Down to up)", muscle_group: "core", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Set a cable low. Pull the handle diagonally up and across your body, rotating through your core, then return." },
  { name: "Cable Twist (Up to down)", muscle_group: "core", equipment: "cable", secondary_muscles: ["shoulders"], instructions: "Set a cable high. Pull the handle diagonally down and across your body, rotating through your core, then return." },
  { name: "Crunch (Machine)", muscle_group: "core", equipment: "machine", secondary_muscles: [], instructions: "Sit at a crunch machine. Curl your torso forward against the resistance, squeezing the abs, then slowly return." },
  { name: "Crunch (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back holding a weight plate at your chest. Curl your upper body toward your knees, then lower." },
  { name: "Decline Crunch (Weighted)", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on a decline bench holding a weight plate. Crunch your upper body toward your knees, then lower." },
  { name: "Dragonfly", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on a bench gripping behind your head. Raise your whole body up in a lever position, lowering slowly to parallel, then return." },
  { name: "Elbow to Knee", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with hands behind your head and knees bent. Crunch and rotate, bringing elbow toward opposite knee, alternating." },
  { name: "Calf Extension (Machine)", muscle_group: "calves", equipment: "machine", secondary_muscles: [], instructions: "Sit at a calf extension machine. Press the platform away by extending your ankles, rising onto your toes, then lower." },
  { name: "Calf Press (Machine)", muscle_group: "calves", equipment: "machine", secondary_muscles: [], instructions: "Sit in a leg press machine with only the balls of your feet on the platform. Press up onto your toes, then lower slowly." },
  { name: "Clean", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Pull the barbell from the floor to a front rack position at shoulder height in one explosive movement." },
  { name: "Clean and Jerk", muscle_group: "shoulders", equipment: "barbell", secondary_muscles: ["legs"], instructions: "Clean the bar to shoulder height, then split jerk it overhead. One of the two Olympic lifts." },
  { name: "Clean Pull", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["back"], instructions: "Pull the barbell from the floor with an explosive triple extension of ankles, knees, and hips without completing the catch." },
  { name: "Dumbbell Snatch", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["legs"], instructions: "Hold a dumbbell between your legs. Explosively drive your hips and pull it overhead in one smooth motion." },
  { name: "Frog Jumps", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes"], instructions: "Squat down and touch the floor, then explode forward and upward jumping like a frog. Land and immediately repeat." },
  { name: "Front Lever Hold", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Hang from a bar and raise your body until it is horizontal with the ground, arms straight, and hold the position." },
  { name: "Front Lever Raise", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Hang from a bar. Keeping arms straight, raise your body from hanging to horizontal front lever position, then lower." },
  { name: "Downward Dog", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["shoulders", "legs"], instructions: "Start on hands and knees. Push your hips up and back forming an inverted V, pressing your heels toward the floor. Hold and breathe." },
  { name: "Climbing", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Climb a wall, rope, or structure using your hands and feet, focusing on grip strength and body control." },
  { name: "Cycling", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Pedal a stationary or outdoor bike at your desired resistance and cadence for your target duration." },
  { name: "Elliptical Trainer", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Use an elliptical trainer with a smooth oval stride motion. Adjust resistance and incline as desired." },
  { name: "Farmers Walk", muscle_group: "forearms", equipment: "dumbbell", secondary_muscles: ["back"], instructions: "Hold heavy dumbbells or kettlebells at your sides. Walk for a set distance or time keeping your posture upright." },
  { name: "Chin Up", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Grip a bar with palms facing you (supinated). Pull your chin above the bar, then lower slowly." },
  { name: "Chin Up (Assisted)", muscle_group: "back", equipment: "machine", secondary_muscles: ["biceps"], instructions: "Use an assisted chin-up machine with a supinated grip. Pull your chin above the bar with the machine providing assistance." },
  { name: "Chin Up (Weighted)", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["biceps"], instructions: "Perform a chin-up with a supinated grip while wearing a weight belt or holding a dumbbell between your feet." },
  { name: "Curtsy Lunge (Dumbbell)", muscle_group: "legs", equipment: "dumbbell", secondary_muscles: ["glutes"], instructions: "Hold dumbbells and step one foot diagonally behind the other in a curtsy motion. Lower your back knee, then return to standing." },
  { name: "Dumbbell Squeeze Press", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Lie on a bench pressing two dumbbells together above your chest. Lower them while keeping them in contact, then press back up." },
  // BATCH 7
  { name: "21s Bicep Curl", muscle_group: "biceps", equipment: "barbell", secondary_muscles: [], instructions: "Perform 7 curls from the bottom to halfway, 7 from halfway to the top, then 7 full range curls. That's one set of 21." },
  { name: "Behind the Back Bicep Wrist Curl (Barbell)", muscle_group: "forearms", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell behind your back. Curl your wrists upward, then lower slowly." },
  { name: "Behind the Back Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: ["forearms"], instructions: "Stand facing away from a low cable. Curl the handle up from behind your hip to shoulder height, then lower." },
  { name: "Bicep Curl (Barbell)", muscle_group: "biceps", equipment: "barbell", secondary_muscles: [], instructions: "Hold a barbell with a supinated grip. Curl it up to shoulder height, then lower slowly." },
  { name: "Bicep Curl (Cable)", muscle_group: "biceps", equipment: "cable", secondary_muscles: [], instructions: "Stand at a low cable with a straight bar. Curl it up to shoulder height with a supinated grip, then lower." },
  { name: "Bicep Curl (Dumbbell)", muscle_group: "biceps", equipment: "dumbbell", secondary_muscles: [], instructions: "Hold dumbbells with a supinated grip. Curl them up to shoulder height, then lower slowly." },
  { name: "Bicep Curl (Machine)", muscle_group: "biceps", equipment: "machine", secondary_muscles: [], instructions: "Sit at a bicep curl machine with upper arms on the pad. Curl the handles up, then lower slowly." },
  { name: "Bicep Curl (Suspension)", muscle_group: "biceps", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Hold TRX straps facing the anchor with palms up. Lean back and curl your body toward the anchor, then lower." },
  { name: "Ab Scissors", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with legs raised. Cross your legs alternately in a scissor motion, keeping your lower back pressed to the floor." },
  { name: "Ab Wheel", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Kneel holding an ab wheel. Roll it forward until your body is nearly parallel to the floor, then pull back using your core." },
  { name: "Bicycle Crunch Raised Legs", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Lie on your back with legs raised at 90 degrees. Pedal your legs while rotating your torso to bring elbow to opposite knee." },
  { name: "Aerobics", muscle_group: "core", equipment: "bodyweight", secondary_muscles: [], instructions: "Perform rhythmic aerobic exercises such as step aerobics, dance aerobics, or general cardio movements for sustained activity." },
  { name: "Air Bike", muscle_group: "legs", equipment: "machine", secondary_muscles: [], instructions: "Pedal an air resistance bike, pushing and pulling the handles simultaneously for a full body cardio workout." },
  { name: "Boxing", muscle_group: "shoulders", equipment: "bodyweight", secondary_muscles: ["core"], instructions: "Perform boxing combinations including jabs, crosses, hooks, and uppercuts either on a bag or with a partner." },
  { name: "Arnold Press (Dumbbell)", muscle_group: "shoulders", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Sit holding dumbbells at shoulder height with palms facing you. Press up while rotating palms outward, then reverse on the way down." },
  { name: "Band Pullaparts", muscle_group: "shoulders", equipment: "bands", secondary_muscles: ["back"], instructions: "Hold a resistance band with both hands at shoulder height. Pull it apart by moving hands outward, squeezing rear delts, then return." },
  { name: "Around The World", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["shoulders"], instructions: "Lie on a bench with dumbbells at your sides. Sweep them in a wide arc overhead and back, keeping arms nearly straight throughout." },
  { name: "Bench Press - Close Grip (Barbell)", muscle_group: "triceps", equipment: "barbell", secondary_muscles: ["chest"], instructions: "Lie on a bench with hands close together on the barbell. Lower it to your chest, then press back up, focusing on the triceps." },
  { name: "Bench Press - Wide Grip (Barbell)", muscle_group: "chest", equipment: "barbell", secondary_muscles: ["shoulders"], instructions: "Lie on a bench with hands wider than shoulder-width. Lower the bar to your chest, then press back up." },
  { name: "Bench Press (Barbell)", muscle_group: "chest", equipment: "barbell", secondary_muscles: ["triceps", "shoulders"], instructions: "Lie on a flat bench. Lower a barbell to your chest, then press it back up to full extension." },
  { name: "Bench Press (Cable)", muscle_group: "chest", equipment: "cable", secondary_muscles: ["triceps"], instructions: "Lie on a bench between two low cables. Press the handles up and together above your chest, then lower slowly." },
  { name: "Bench Press (Dumbbell)", muscle_group: "chest", equipment: "dumbbell", secondary_muscles: ["triceps"], instructions: "Lie on a flat bench with dumbbells at chest level. Press them up until arms are extended, then lower slowly." },
  { name: "Bench Press (Smith Machine)", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps"], instructions: "Lie on a bench inside a Smith machine. Lower the bar to your chest, then press back up." },
  { name: "Bench Dip", muscle_group: "triceps", equipment: "bodyweight", secondary_muscles: ["chest", "shoulders"], instructions: "Sit on the edge of a bench with hands gripping the edge. Slide off and lower your body by bending your elbows, then press back up." },
  { name: "Supine Press", muscle_group: "chest", equipment: "machine", secondary_muscles: ["triceps", "shoulders"], instructions: "Lie on a supine press machine. Press the handles up from chest level until arms are extended, then lower slowly." },
  { name: "Back Extension (Hyperextension)", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["glutes", "legs"], instructions: "Lock your feet in a hyperextension bench. Lower your torso toward the floor, then raise it back to parallel using your lower back." },
  { name: "Back Extension (Machine)", muscle_group: "back", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Sit in a back extension machine. Push back against the pad by extending your spine, then return to the starting position." },
  { name: "Back Extension (Weighted Hyperextension)", muscle_group: "back", equipment: "bodyweight", secondary_muscles: ["glutes", "legs"], instructions: "Lock your feet in a hyperextension bench holding a weight plate. Lower your torso, then raise it using your lower back." },
  { name: "Bent Over Row (Band)", muscle_group: "back", equipment: "bands", secondary_muscles: ["biceps"], instructions: "Stand on a resistance band and hinge forward. Row both handles up to your hips simultaneously, squeezing shoulder blades." },
  { name: "Bent Over Row (Barbell)", muscle_group: "back", equipment: "barbell", secondary_muscles: ["biceps"], instructions: "Hinge forward holding a barbell. Row it to your lower chest or upper abdomen, then lower with control." },
  { name: "Bent Over Row (Dumbbell)", muscle_group: "back", equipment: "dumbbell", secondary_muscles: ["biceps"], instructions: "Hinge forward holding dumbbells. Row them to your sides simultaneously, squeezing shoulder blades together, then lower." },
  { name: "Bird Dog", muscle_group: "glutes", equipment: "bodyweight", secondary_muscles: ["core", "back"], instructions: "On hands and knees, simultaneously extend the opposite arm and leg until both are parallel to the floor, then return and alternate." },
  { name: "Assisted Pistol Squats", muscle_group: "legs", equipment: "bodyweight", secondary_muscles: ["glutes", "core"], instructions: "Hold a TRX strap or pole for balance. Perform a single-leg squat as deep as possible, using the support only as needed." },
  { name: "Belt Squat (Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Attach a belt around your hips to a belt squat machine. Stand on the platforms and squat down, then drive back up." },
  { name: "Box Squat (Barbell)", muscle_group: "legs", equipment: "barbell", secondary_muscles: ["glutes"], instructions: "Set a box behind you with a barbell on your back. Squat back and down to sit on the box briefly, then drive back up." },
  { name: "Bulgarian Split Squat (Smith Machine)", muscle_group: "legs", equipment: "machine", secondary_muscles: ["glutes"], instructions: "Place one foot elevated behind you on a bench inside a Smith machine. Lower your back knee toward the floor, then drive back up." },
  { name: "Ball Slams", muscle_group: "core", equipment: "bodyweight", secondary_muscles: ["shoulders"], instructions: "Hold a medicine ball overhead. Slam it down to the floor with full force, catch it on the bounce, and repeat." },
];

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const exercises = await base44.asServiceRole.entities.Exercise.list('-created_date', 2000);

    // Update images on existing exercises
    let imgUpdated = 0;
    for (const exercise of exercises) {
      const imgs = IMAGES[exercise.name];
      if (imgs) {
        await base44.asServiceRole.entities.Exercise.update(exercise.id, {
          image_url: BASE_URL + imgs.light,
          image_url_dark: BASE_URL + imgs.dark,
        });
        imgUpdated++;
      }
    }

    // Add new exercises (skip if already exists by name)
    const existingNames = new Set(exercises.map(e => e.name.toLowerCase()));
    let added = 0, skipped = 0;
    for (const ex of NEW_EXERCISES) {
      if (existingNames.has(ex.name.toLowerCase())) {
        skipped++;
      } else {
        await base44.asServiceRole.entities.Exercise.create(ex);
        existingNames.add(ex.name.toLowerCase());
        added++;
        await sleep(120);
      }
    }

    return Response.json({ success: true, images_updated: imgUpdated, added, skipped });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});