import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// Exhaustive map of exercise name -> precise anatomical description for image generation
const EXERCISE_DESCRIPTIONS = {
  // CHEST
  "Bench Press": "a flat bench barbell bench press, figure lying horizontally on a flat bench, barbell held with wide grip directly over chest, elbows flared at roughly 75 degrees",
  "Bench Press (Barbell)": "a flat bench barbell bench press, figure lying horizontally on a flat bench, barbell held with wide grip directly over chest, elbows flared at roughly 75 degrees",
  "Bench Press - Wide Grip (Barbell)": "a wide-grip flat bench barbell bench press, figure lying on a flat bench, barbell gripped wider than shoulder width, lowered to mid-chest",
  "Bench Press - Close Grip (Barbell)": "a close-grip flat bench barbell bench press, hands shoulder-width apart on barbell, elbows close to body, pressing from flat bench",
  "Incline Bench Press": "an incline barbell bench press on a bench angled upward 30-45 degrees, barbell lowered to upper chest, elbows at 75 degrees",
  "Incline Bench Press (Barbell)": "an incline barbell bench press on a bench angled upward 30-45 degrees, barbell lowered to upper chest, elbows at 75 degrees",
  "Decline Bench Press": "a decline barbell bench press, figure lying on downward-angled bench with head lower than feet, barbell lowered to lower chest",
  "Decline Bench Press (Barbell)": "a decline barbell bench press, figure lying on downward-angled bench with head lower than feet, barbell lowered to lower chest",
  "Dumbbell Chest Press": "a flat dumbbell chest press, figure lying on flat bench, two dumbbells pressed upward from chest level, elbows flared outward",
  "Bench Press (Dumbbell)": "a flat dumbbell chest press, figure lying on flat bench, two dumbbells pressed upward from chest level, elbows flared outward",
  "Incline Dumbbell Press": "an incline dumbbell press on a 30-45 degree angled bench, two dumbbells pressed upward from upper chest, arms at an angle",
  "Chest Fly (Dumbbell)": "a dumbbell chest fly lying on a flat bench, arms extended wide in a hugging arc, dumbbells lowered to sides and raised together over chest",
  "Incline Chest Fly (Dumbbell)": "a dumbbell fly on an incline bench angled 30-45 degrees, arms extended wide, dumbbells lowered to sides and raised over upper chest",
  "Decline Chest Fly (Dumbbell)": "a dumbbell fly on a decline bench angled downward, arms extended wide, dumbbells lowered to sides and raised over lower chest",
  "Cable Fly": "a cable chest fly at a cable machine, figure standing between two cable pulleys, arms extended out to sides and brought together in front of chest",
  "Cable Fly Crossovers": "a cable chest fly crossover at a cable machine, figure standing between two high pulleys, arms pulled down and across in front of chest",
  "Low Cable Fly Crossovers": "a low cable fly crossover with two low pulleys, figure standing between cables, arms raised upward and together in front of chest",
  "Chest Fly (Machine)": "a chest fly on a pec deck machine, figure seated at machine, arms pressed inward on pads against resistance",
  "Pec Deck Machine": "a pec deck chest fly machine, figure seated upright, forearms on pads, arms pressed together in front of chest",
  "Butterfly (Pec Deck)": "a butterfly pec deck chest fly, figure seated at machine with arms on padded levers, arms squeezing together in front",
  "Push-ups": "a standard push-up, figure in plank position with hands shoulder-width apart, body lowered toward floor with elbows bending",
  "Push Up": "a standard push-up, figure in plank position with hands shoulder-width apart, body lowered toward floor with elbows bending",
  "Chest Dip": "a chest dip on parallel bars, figure leaning forward at about 30 degrees, elbows flared out, body lowering between bars",
  "Chest Dip (Weighted)": "a weighted chest dip on parallel bars with weight belt attached, figure leaning forward, elbows flared, body lowering between bars",
  "Chest Dip (Assisted)": "an assisted chest dip on an assisted dip machine, figure leaning forward with knees or feet on support pad, lowering between bars",
  "Close Grip Bench Press": "a close-grip barbell bench press on flat bench, hands shoulder-width apart, elbows tucked close to body throughout movement",
  "Bench Press (Cable)": "a cable chest press lying on a flat bench between two low cable pulleys, pressing handles upward and together over chest",
  "Bench Press (Smith Machine)": "a flat bench press in a Smith machine, figure lying on flat bench, bar on fixed track pressed overhead",
  "Incline Bench Press (Smith Machine)": "an incline bench press in a Smith machine on a 30-45 degree bench, bar on fixed track pressed from upper chest",
  "Decline Bench Press (Smith Machine)": "a decline bench press in a Smith machine, figure on downward-angled bench, bar on fixed track pressed from lower chest",
  "Decline Bench Press (Dumbbell)": "a decline dumbbell bench press, figure lying on downward-angled bench, two dumbbells pressed from lower chest",
  "Decline Bench Press (Machine)": "a decline chest press at a machine with a downward-angled seat, pressing handles forward from lower chest position",
  "Hex Press (Dumbbell)": "a hex press lying on flat bench, two dumbbells pressed together vertically with neutral grip, elbows close to body throughout",
  "Dumbbell Squeeze Press": "a squeeze press lying on flat bench, two dumbbells pressed together while pushing upward, maintaining tension between them",
  "Feet Up Bench Press (Barbell)": "a barbell bench press lying on a flat bench with feet raised off the floor and tucked up, lower back flat",
  "Floor Press (Barbell)": "a barbell floor press lying on the floor, arms bent with elbows resting on floor, barbell pressed upward",
  "Floor Press (Dumbbell)": "a dumbbell floor press lying on the floor, arms bent with elbows resting on floor, two dumbbells pressed upward",
  "Chest Press (Band)": "a resistance band chest press, figure holding band handles at chest level, pressing forward horizontally",
  "Chest Press (Machine)": "a seated chest press machine, figure sitting upright, pressing handles forward from chest level",
  "Iso-Lateral Chest Press (Machine)": "a seated iso-lateral chest press at a machine, each arm pressing one handle independently forward from chest",
  "Incline Chest Press (Machine)": "an incline chest press on a machine with upward-angled seat, pressing handles upward and outward from upper chest",
  "Chest Fly (Band)": "a resistance band chest fly, figure standing holding band handles, arms extended out and brought together in front of chest",
  "Chest Fly (Suspension)": "a suspension trainer chest fly, figure leaning forward holding rings or straps, arms extended outward and pulled together",
  "Chest Supported Incline Row (Dumbbell)": "a chest-supported incline dumbbell row, figure lying face down on an incline bench, rowing two dumbbells up toward hips",
  "Plyometric Push Up": "a plyometric push-up, figure in push-up position with hands leaving the floor explosively, hands airborne at the top",
  "Clap Push Ups": "a clap push-up, figure in push-up position with hands airborne and clapping together between reps",
  "Decline Push Up": "a decline push-up, figure with feet elevated on a bench, hands on floor, body at a downward angle, lowering chest to floor",
  "Incline Push Ups": "an incline push-up, figure with hands on an elevated surface like a bench, feet on floor, body at an upward angle",
  "Diamond Push Up": "a diamond push-up, hands forming a diamond shape under chest, elbows pointing outward, body lowering toward hands",
  "Pike Push Up": "a pike push-up, figure in a pike position with hips raised high, arms bending to lower head toward floor",
  "One Arm Push Up": "a one-arm push-up, figure in push-up position supporting entire body on one hand with the other behind back",
  "Kneeling Push Up": "a kneeling push-up, figure on knees with hands on floor, body lowering from knees rather than toes",
  "Push Up (Band)": "a push-up with a resistance band across the upper back, figure in push-up position pressing against added band resistance",
  "Push Up (Suspension)": "a suspension push-up using rings or TRX straps, figure holding unstable straps and performing a push-up",

  // BACK
  "Pull-ups": "a strict pull-up, figure hanging from a bar with overhand grip, arms fully extended at bottom, chin above bar at top",
  "Pull Up": "a strict pull-up, figure hanging from a bar with overhand grip, arms fully extended at bottom, chin above bar at top",
  "Chin-ups": "a chin-up with underhand supinated grip on a bar, figure hanging with palms facing toward them, chin pulled above bar",
  "Chin Up": "a chin-up with underhand supinated grip on a bar, figure hanging with palms facing toward them, chin pulled above bar",
  "Chin Up (Assisted)": "an assisted chin-up on an assisted pull-up machine, figure with knees or feet on support platform, pulling up with underhand grip",
  "Chin Up (Weighted)": "a weighted chin-up with a dip belt hanging weight from hips, underhand grip on bar, full range of motion",
  "Pull Up (Assisted)": "an assisted pull-up on an assisted pull-up machine, figure with knees or feet on support, overhand grip pull-up",
  "Pull Up (Weighted)": "a weighted pull-up with a dip belt hanging weight from hips, overhand grip on bar, full range of motion",
  "Wide Grip Pull Up": "a wide-grip pull-up with hands gripping bar wider than shoulder width, overhand grip, full hang to chin over bar",
  "Kipping Pull Up": "a kipping pull-up, figure swinging body using hip momentum to assist pulling chin above the bar",
  "Negative Pull Up": "a negative pull-up, figure at the top position with chin above bar, slowly lowering down to a dead hang",
  "Lat Pulldown": "a lat pulldown at a cable machine, figure seated facing machine, pulling a wide bar down to upper chest from overhead",
  "Lat Pulldown (Cable)": "a lat pulldown at a cable machine, figure seated facing machine, pulling a wide bar down to upper chest from overhead",
  "Lat Pulldown (Band)": "a lat pulldown using resistance bands, figure kneeling or seated, pulling band handles down from overhead toward chest",
  "Lat Pulldown (Machine)": "a lat pulldown at a machine, figure seated, pulling a bar down from overhead to upper chest",
  "Lat Pulldown - Close Grip (Cable)": "a close-grip lat pulldown at a cable machine, figure seated with narrow grip on V-bar or close attachment, pulling down to chest",
  "Barbell Row": "a barbell bent-over row, figure hinged forward with nearly horizontal torso, barbell pulled up to lower chest or upper abdomen, elbows driving back",
  "Bent Over Row (Barbell)": "a barbell bent-over row, figure hinged forward with nearly horizontal torso, barbell pulled up to lower chest or upper abdomen, elbows driving back",
  "Bent Over Row (Dumbbell)": "a dumbbell bent-over row, figure hinged forward, two dumbbells rowed simultaneously toward hips, elbows driving back",
  "Bent Over Row (Band)": "a resistance band bent-over row, figure standing on band hinged forward, pulling handles up to hips simultaneously",
  "Single Arm Dumbbell Row": "a single-arm dumbbell row, figure with one knee and hand on a bench for support, other hand rowing a dumbbell up to hip",
  "Dumbbell Row": "a single-arm dumbbell row, figure with one knee and hand on a bench for support, other hand rowing a dumbbell up to hip",
  "Seated Cable Row": "a seated cable row, figure seated on cable row machine with feet on platform, cable pulled to abdomen with elbows driving back",
  "Machine Row": "a seated chest-supported row machine, figure seated with chest against pad, pulling handles toward torso",
  "Seated Row (Machine)": "a seated row machine, figure seated upright gripping handles, pulling handles toward abdomen with elbows back",
  "T-Bar Row": "a T-bar row, figure bent over straddling a landmine bar with both hands on a neutral grip, bar rowed up to chest",
  "Meadows Row": "a Meadows row in a landmine setup, figure in a staggered stance next to the landmine bar, single-arm pulling the plate end toward hip",
  "Wide Grip Cable Row": "a wide-grip cable row seated at a cable machine, figure seated holding a wide grip bar, pulling it wide to lower ribs",
  "Pendlay Row": "a Pendlay row, figure completely horizontal with barbell resting on floor between reps, explosive pull to lower chest",
  "Single Arm Cable Row": "a single-arm cable row, figure seated or standing at a cable machine, one arm pulling a handle toward torso",
  "Inverted Row": "an inverted row using a bar at waist height, figure hanging horizontally under the bar with straight body, pulling chest up to bar",
  "Low Row (Suspension)": "a suspension trainer low row, figure leaning back holding TRX handles, pulling chest up toward handles",
  "Hyperextension": "a hyperextension exercise on a GHD or hyperextension bench, figure bent at hips with ankles locked, raising torso from horizontal to aligned",
  "Back Extension (Hyperextension)": "a hyperextension on a 45-degree hyperextension bench, figure bent at hips with lower body secured, raising torso upward",
  "Back Extension (Weighted Hyperextension)": "a weighted hyperextension holding a weight plate on a hyperextension bench, figure raising torso from bent to aligned position",
  "Back Extension (Machine)": "a back extension on a dedicated machine, figure seated with back against pad, extending torso rearward against resistance",
  "Reverse Hyper Extension": "a reverse hyperextension on a special bench, upper body flat, legs extended and lifted behind in an arc",
  "Reverse Hyper (GHD)": "a reverse hyperextension on a GHD machine, figure face down with upper body secured, legs raised behind in an arc",
  "Good Morning (Barbell)": "a barbell good morning, figure standing with barbell across upper back, hinging forward at hips until torso is nearly horizontal",
  "Straight Arm Pulldown (Cable)": "a straight-arm cable pulldown, figure standing facing a high cable, arms straight pulling the bar down from overhead to thighs",
  "Dumbbell Pullover": "a dumbbell pullover lying across or on a flat bench, arms extended overhead holding a single dumbbell, pulled in an arc from behind head to over chest",
  "Barbell Pullover": "a barbell pullover lying on a flat bench, arms extended holding a barbell, pulled in an arc from behind head to over chest",
  "Cable Pullover": "a cable pullover at a cable machine, figure standing or kneeling, pulling a rope or bar in an arc from overhead down to hips",
  "Gorilla Row (Kettlebell)": "a gorilla row with two kettlebells on the floor, figure bent over in a squat-hinge position, alternating rowing each kettlebell up",
  "Rack Pull": "a rack pull starting from knee height in a power rack, figure pulling barbell up from elevated pins to a standing lockout",
  "Superman": "a superman exercise lying face down on the floor, arms and legs extended, lifting both arms and legs off the floor simultaneously",
  "Glute Ham Raise": "a glute-ham raise on a GHD machine, figure with feet secured at the foot plate, lowering torso forward and curling back up",
  "Rowing Machine": "a rowing machine exercise, figure seated on rowing machine with arms driving back while legs push, sliding seat moving backward",
  "Rope Climb": "a rope climb, figure gripping a vertical rope with hands above head, feet using rope for purchase, pulling upward",
  "Iso-Lateral High Row (Machine)": "an iso-lateral high row machine, figure seated pulling two independent arms down and toward chest from an elevated position",
  "Iso-Lateral Low Row": "an iso-lateral low row machine, figure seated pulling two independent handles toward torso from a low position",
  "Iso-Lateral Row (Machine)": "an iso-lateral row machine, figure seated pulling independent arm handles toward torso",
  "Kneeling Pulldown (Band)": "a kneeling band pulldown, figure kneeling with resistance band attached overhead, pulling band down toward chest",
  "Landmine Row": "a landmine row, figure bent over gripping the plate end of a landmine bar, rowing it up toward hip with one arm",
  "Dead Hang": "a dead hang, figure hanging from a pull-up bar with arms fully extended and straight, feet off the floor",

  // SHOULDERS
  "Shoulder Press": "a standing barbell overhead press, barbell pressed from front rack position overhead until arms are fully extended",
  "Overhead Press": "a standing barbell overhead press, barbell pressed from front rack position overhead until arms are fully extended",
  "Barbell Overhead Press": "a standing barbell overhead press, barbell pressed from front rack position overhead until arms are fully extended",
  "Overhead Press (Barbell)": "a standing barbell overhead press, barbell pressed from front rack position overhead until arms are fully extended",
  "Overhead Press (Dumbbell)": "a seated or standing dumbbell overhead press, two dumbbells pressed from shoulder height overhead until arms extended",
  "Dumbbell Shoulder Press": "a seated dumbbell overhead press, two dumbbells pressed from shoulder height overhead until arms fully extended",
  "Overhead Press (Smith Machine)": "an overhead press in a Smith machine, figure pressing bar from shoulder height overhead on fixed rails",
  "Machine Shoulder Press": "a seated shoulder press on a machine, figure pressing handles upward overhead from shoulder height",
  "Shoulder Press (Machine)": "a seated shoulder press machine, figure seated pressing handles overhead from shoulder height",
  "Seated Overhead Press (Machine)": "a seated overhead press at a shoulder press machine, pressing handles from shoulder height upward overhead",
  "Arnold Press": "an Arnold press with dumbbells, starting with palms facing inward at chin height, rotating outward while pressing overhead",
  "Arnold Press (Dumbbell)": "an Arnold press with dumbbells, starting with palms facing inward at chin height, rotating outward while pressing overhead",
  "Lateral Raise": "a dumbbell lateral raise, figure standing with arms slightly bent, dumbbells raised out to sides to shoulder height",
  "Lateral Raise (Dumbbell)": "a dumbbell lateral raise, figure standing with arms slightly bent, dumbbells raised out to sides to shoulder height",
  "Lateral Raise (Cable)": "a cable lateral raise, figure standing to the side of a cable machine, one arm raising a handle out to shoulder height",
  "Cable Lateral Raise": "a cable lateral raise, figure standing sideways at a cable machine, arm pulling a low cable handle out and up to shoulder height",
  "Lateral Raise (Band)": "a resistance band lateral raise, figure standing on band with arms at sides, raising handles out to shoulder height",
  "Lateral Raise (Machine)": "a lateral raise at a machine, figure seated with arms on pads, raising arms out to shoulder height against resistance",
  "Front Raise": "a dumbbell front raise, figure standing with dumbbells at thighs, one or both arms raised forward to shoulder height",
  "Front Raise (Dumbbell)": "a dumbbell front raise, figure standing with dumbbells at thighs, one or both arms raised forward to shoulder height",
  "Front Raise (Barbell)": "a barbell front raise, figure standing holding barbell at thighs, raising it forward to shoulder height with straight arms",
  "Front Raise (Cable)": "a cable front raise, figure standing facing away from low cable, pulling handle up and forward to shoulder height",
  "Front Raise (Band)": "a resistance band front raise, figure standing on band, pulling handle upward in front to shoulder height",
  "Front Raise (Suspension)": "a suspension trainer front raise, figure leaning back holding handles, raising arms forward and upward",
  "Rear Delt Fly": "a bent-over rear delt fly, figure hinged forward horizontally, arms raised out to sides with elbows slightly bent, targeting rear deltoids",
  "Rear Delt Fly (Dumbbell)": "a bent-over rear delt dumbbell fly, figure hinged forward, arms raised out to sides targeting rear deltoids",
  "Rear Delt Fly (Cable)": "a cable rear delt fly, figure bent over at a cable machine, cable handles pulled out to sides from crossed position",
  "Rear Delt Fly (Machine)": "a rear delt fly on a pec deck or rear delt machine, figure seated with arms extended, pressing handles rearward",
  "Chest Supported Reverse Fly (Dumbbell)": "a chest-supported dumbbell reverse fly, figure lying face down on incline bench, arms raised out to sides targeting rear deltoids",
  "Chest Supported Y Raise (Dumbbell)": "a Y raise lying face down on incline bench, arms raised diagonally outward in a Y shape, targeting lower traps and rear delts",
  "Reverse Fly (Dumbbell)": "a bent-over reverse fly with dumbbells, figure hinged forward, arms raised laterally targeting rear deltoids",
  "Face Pull": "a cable face pull with a rope attachment at head height, figure pulling rope toward face with elbows high and flared out",
  "Upright Row": "a barbell upright row, figure standing holding barbell with close grip, pulling it straight up along torso to chin height, elbows high",
  "Upright Row (Barbell)": "a barbell upright row, figure standing holding barbell with close grip, pulling it straight up along torso to chin height, elbows high",
  "Upright Row (Dumbbell)": "a dumbbell upright row, figure standing holding dumbbells in front of thighs, pulling them straight up to chin with elbows high",
  "Barbell Shrug": "a barbell shrug, figure standing holding barbell with straight arms at thighs, shrugging shoulders directly upward toward ears",
  "Shrug (Dumbbell)": "a dumbbell shrug, figure standing with dumbbells at sides, shrugging shoulders directly upward toward ears",
  "Band Pull Apart": "a band pull-apart, figure standing holding a resistance band in front with straight arms, pulling band apart to chest level",
  "Push Press": "a push press, figure with barbell at shoulders, slight knee dip then explosive drive pressing barbell overhead using legs",
  "Thruster (Barbell)": "a barbell thruster, figure performing a front squat transitioning directly into an overhead press in one fluid movement",
  "Landmine Press": "a landmine press, figure in a half-kneeling or standing position, pressing the plate end of a landmine bar upward and forward overhead",
  "Landmine 180": "a landmine 180, figure standing holding landmine bar with both hands overhead, rotating it in a wide arc from one side to the other",
  "Kettle Bell Press": "a kettlebell overhead press, figure standing or seated pressing a kettlebell from shoulder height overhead with one arm",
  "Kettlebell Press": "a kettlebell overhead press, figure standing pressing a single kettlebell from shoulder rack position to overhead lockout",
  "Kettlebell Shoulder Press": "a kettlebell shoulder press, figure pressing one or two kettlebells from shoulder height to overhead lockout",
  "Around The World": "an around-the-world movement with a plate or dumbbell, figure holding weight and rotating it in a large circle around the head",
  "Kettlebell Halo": "a kettlebell halo, figure standing holding a kettlebell at chest, circling it around the head in alternating directions",
  "Overhead Plate Raise": "an overhead plate raise, figure standing holding a weight plate in front, raising it with straight arms overhead",
  "Dumbbell Snatch": "a dumbbell snatch, figure explosively pulling a single dumbbell from below the hips in one movement overhead to a locked-out position",
  "Hang Snatch": "a hang snatch with barbell, figure starting from a standing position with bar at hips, explosively pulling it overhead in one movement",
  "Snatch (Barbell)": "a barbell snatch, figure in the catch position with a wide grip, barbell locked overhead with arms fully extended",
  "Power Snatch": "a power snatch, figure pulling barbell from floor explosively overhead with a high pull and punch, catching with arms extended",
  "Snatch Pull": "a snatch pull with a wide grip barbell, figure in the high pull position with bar at hip height, traps and lats engaged",
  "Kettlebell Snatch": "a kettlebell snatch, figure explosively swinging a kettlebell from below hips to an overhead lockout with one arm",

  // BICEPS
  "Barbell Curl": "a standing barbell bicep curl, figure standing upright gripping a barbell with a supinated underhand grip, curling it from thighs to shoulders",
  "Bicep Curl (Barbell)": "a standing barbell bicep curl, figure standing upright gripping a barbell with a supinated underhand grip, curling it from thighs to shoulders",
  "Dumbbell Curl": "a standing dumbbell bicep curl, figure standing with dumbbells at sides, curling them up with supinated grip",
  "Bicep Curl (Dumbbell)": "a standing dumbbell bicep curl, figure curling one or two dumbbells with supinated grip from hip to shoulder",
  "Seated Dumbbell Curl": "a seated dumbbell bicep curl, figure seated on a bench, alternately curling dumbbells with supinated grip",
  "Hammer Curl": "a hammer curl with dumbbells, figure standing with neutral palms-facing grip, curling dumbbells upward without rotating wrists",
  "Hammer Curl (Dumbbell)": "a hammer curl with dumbbells, figure standing with neutral palms-facing grip, curling dumbbells upward without rotating wrists",
  "Hammer Curl (Band)": "a resistance band hammer curl, figure standing on band, pulling handles upward with neutral palms-facing grip",
  "Hammer Curl (Cable)": "a cable hammer curl, figure standing at a cable machine with a rope attachment, pulling rope upward with neutral grip",
  "Cross Body Hammer Curl": "a cross-body hammer curl, figure standing, curling dumbbell across body toward opposite shoulder with neutral grip",
  "Preacher Curl": "a preacher curl, figure seated at a preacher curl bench with upper arm resting on the angled pad, curling a barbell or dumbbell up",
  "Preacher Curl (Barbell)": "a preacher curl with a barbell on a preacher curl bench, upper arms on angled pad, curling barbell from extended to contracted position",
  "Preacher Curl (Dumbbell)": "a preacher curl with a single dumbbell on a preacher bench, upper arm on angled pad, full range of motion curl",
  "Preacher Curl (Cable)": "a preacher curl using a cable with a curl attachment, upper arm resting on the preacher pad, cable tension throughout",
  "Preacher Curl (Machine)": "a preacher curl on a machine, figure seated with upper arms on angled pad, gripping machine handles and curling",
  "Concentration Curl": "a concentration curl, figure seated on bench leaning forward, single dumbbell curled with elbow braced against inner thigh",
  "Cable Curl": "a standing cable curl, figure facing a low cable machine holding a straight bar with supinated grip, curling upward",
  "Bicep Curl (Cable)": "a standing cable curl, figure at low cable machine, bar attached to low pulley, curling with supinated grip toward shoulders",
  "Incline Dumbbell Curl": "an incline dumbbell curl, figure seated on an incline bench leaning back, arms hanging behind torso, curling dumbbells upward",
  "Spider Curl": "a spider curl with dumbbells, figure lying face down on an incline bench, arms hanging straight down, curling dumbbells straight up",
  "Bayesian Curl": "a Bayesian curl with a cable machine, figure standing with the cable attached behind them, slight forward lean, single arm curling with the bicep fully contracted",
  "Behind the Back Curl (Cable)": "a behind-the-back cable curl, figure standing with a low cable behind them, arm reaching back and curling forward",
  "Reverse Curl": "a reverse curl, figure standing with a barbell gripped in a pronated overhand position, curling upward with forearms engaged",
  "Reverse Curl (Barbell)": "a reverse curl with a barbell, hands in overhand pronated grip, curling barbell upward from hip to shoulder height",
  "Reverse Curl (Cable)": "a reverse cable curl, figure at cable machine with a bar in overhand pronated grip, curling upward",
  "Reverse Curl (Dumbbell)": "a reverse dumbbell curl, figure standing with dumbbells in overhand pronated grip, curling upward targeting forearms",
  "21s Bicep Curl": "a 21s bicep curl exercise with a barbell, showing the split-range concept: lower half, upper half, and full range curls",
  "Zottman Curl": "a Zottman curl, figure curling dumbbells up with supinated grip then rotating to pronated grip at the top and lowering down",
  "Drag Curl": "a drag curl with a barbell, figure pulling barbell up along the body in a dragging motion with elbows moving back",
  "EZ Bar Biceps Curl": "an EZ bar bicep curl, figure standing holding an EZ curl bar with angled grip, curling from hip to shoulder",
  "Overhead Cable Curl": "an overhead cable curl, figure with both arms raised out to sides at a cable crossover, curling inward toward ears",
  "Bicep Curl (Machine)": "a machine bicep curl, figure seated at a preacher-style machine, gripping handles and curling with consistent resistance",
  "Machine Bicep Curl": "a machine bicep curl, figure seated at a dedicated curl machine, arms on pad, curling handles upward",
  "Bicep Curl (Suspension)": "a suspension trainer bicep curl, figure leaning back holding TRX handles, curling body upward by bending elbows",
  "Kettlebell Curl": "a kettlebell bicep curl, figure standing holding a kettlebell by the handle, curling it upward with supinated grip",
  "Behind the Back Bicep Wrist Curl (Barbell)": "a behind-the-back barbell wrist curl, figure holding barbell behind the back, curling wrists upward to work forearms",

  // TRICEPS
  "Tricep Pushdown": "a cable tricep pushdown, figure standing at high cable machine with a straight bar, arms pressing bar downward keeping elbows fixed at sides",
  "Tricep Pushdown (Cable Bar)": "a cable tricep pushdown with a straight bar attached to high pulley, arms pressing down with elbows fixed at sides",
  "Tricep Pushdown (Cable Rope)": "a cable tricep pushdown with a rope attachment, figure pulling rope ends downward and outward, elbows fixed at sides",
  "Tricep Pushdown (V-Bar)": "a cable tricep pushdown with a V-bar attachment, elbows fixed at sides, pressing downward to full extension",
  "Skull Crusher": "a skull crusher lying on a flat bench, barbell or EZ bar lowered toward the forehead with elbows pointing up, then extended",
  "Skull Crusher (EZ Bar)": "an EZ bar skull crusher lying on a flat bench, bar lowered toward forehead with elbows pointing up, then pressed back up",
  "Skull Crusher (Dumbbell)": "a dumbbell skull crusher lying on a flat bench, dumbbells lowered toward temples with elbows pointing up, then extended",
  "JM Press (Barbell)": "a JM Press lying on a flat bench, close-grip barbell lowered to throat area with elbows partially tucked, pressing back up",
  "Overhead Tricep Extension": "an overhead tricep extension, figure with arms overhead holding a dumbbell or EZ bar behind the head, extending arms upward",
  "Overhead Tricep Extension (Cable)": "an overhead cable tricep extension, figure bent forward or kneeling at a cable, rope or bar pulled from above overhead behind head",
  "Overhead Tricep Extension (Dumbbell)": "a seated overhead dumbbell tricep extension, figure seated holding a single dumbbell overhead with both hands, lowering it behind head",
  "Overhead Tricep Extension (EZ Bar)": "a seated overhead EZ bar tricep extension, figure holding EZ bar overhead, lowering it behind head with elbows pointing up",
  "Tricep Extension (Band)": "a resistance band overhead tricep extension, figure holding band overhead and extending arms to work triceps",
  "Dumbbell Kickback": "a dumbbell tricep kickback, figure hinged forward with upper arm parallel to floor, extending forearm backward to lockout",
  "Tricep Kickback (Dumbbell)": "a dumbbell tricep kickback, figure in a hinge position, upper arm fixed parallel to floor, forearm kicking back to full extension",
  "Cable Kickback": "a cable tricep kickback, figure bent forward at a low cable, upper arm fixed, extending forearm rearward against cable tension",
  "Tricep Dip": "a tricep dip on parallel bars, figure upright with arms fully extended, lowering body by bending elbows close to sides",
  "Tricep Dip (Parallel Bars)": "a tricep dip on parallel bars, figure upright between bars, elbows bending close to body as figure lowers, elbows tracking back",
  "Bench Dip": "a bench dip, figure with hands on a bench behind them, feet forward, lowering hips toward floor by bending elbows",
  "Floor Triceps Dip": "a floor tricep dip, figure with hands on floor behind them, feet and hips raised, performing a dip motion",
  "Seated Tricep Dip": "a seated tricep dip, figure seated on a chair or bench edge, hands gripping the edge, lowering and raising by bending elbows",
  "Ring Dip": "a ring dip on gymnastic rings, figure between rings, lowering body with rings slightly flared, then pressing back up",

  // LEGS - QUADS
  "Squat": "a barbell back squat, barbell resting on upper traps, figure squatting to parallel or below with standard stance",
  "Squat (Barbell)": "a barbell back squat, barbell resting on upper traps, figure squatting to parallel or below with standard stance",
  "Squat (Bodyweight)": "a bodyweight squat, figure with no weight, squatting down to parallel with arms extended forward for balance",
  "Squat (Dumbbell)": "a goblet squat holding a dumbbell at chest height, figure squatting down with heels hip-width apart",
  "Squat (Band)": "a resistance band squat, figure standing on band with handles at shoulders, performing a squat",
  "Squat (Smith Machine)": "a Smith machine squat, bar in a fixed track, figure performing a squat with feet slightly forward",
  "Front Squat": "a barbell front squat, bar resting on front of shoulders in a front rack with elbows high, figure squatting down to parallel",
  "Front Squat (Barbell)": "a barbell front squat, bar in front rack position on anterior deltoids with elbows high, figure performing a deep squat",
  "Hack Squat": "a hack squat on an angled machine, figure with back against the pad and feet on a forward-inclined platform, lowering the weighted sled",
  "Hack Squat (Machine)": "a hack squat on an angled machine with feet on a forward platform, figure's back against pad, bending knees as the sled lowers",
  "Leg Press": "a leg press on an angled leg press machine, figure seated with back against seat, pushing a weighted platform away with both legs",
  "Leg Press (Machine)": "a leg press on an angled sled machine, figure seated with feet on platform, extending legs to press weight upward",
  "Leg Press Horizontal (Machine)": "a horizontal leg press, figure seated upright pushing a vertical platform forward with both legs extended",
  "Box Squat (Barbell)": "a barbell box squat, barbell on upper traps, figure squatting down to sit briefly on a box behind them, then driving back up",
  "Pause Squat (Barbell)": "a paused barbell back squat, figure holding a deep squat position at the bottom with barbell on upper traps",
  "Goblet Squat": "a goblet squat holding a single dumbbell or kettlebell vertically at chest height, figure squatting deep with elbows inside knees",
  "Kettlebell Goblet Squat": "a kettlebell goblet squat, figure holding a kettlebell by the horns at chest height, squatting deeply",
  "Sumo Squat": "a sumo squat with wide stance and toes pointed outward, figure squatting down with knees tracking over toes",
  "Lateral Squat": "a lateral squat, figure taking a wide step to one side and bending that knee, keeping the other leg straight",
  "Full Squat": "a full depth barbell back squat, figure squatting well below parallel with barbell on upper traps",
  "Overhead Squat (Barbell)": "an overhead barbell squat, figure holding barbell locked overhead with wide grip, squatting to full depth",
  "Sissy Squat": "a sissy squat, figure leaning back with ankles secured, bending at the knees while keeping hips extended and torso angled back",
  "Wall Sit": "a wall sit, figure sitting against a wall with thighs parallel to the floor, knees at 90 degrees, back flat against wall",
  "Zercher Squat": "a Zercher squat, figure holding a barbell in the crooks of both elbows at waist height, squatting down",
  "Jump Squat": "a jump squat, figure dropping into a squat and explosively jumping upward from the squat position",
  "Squat Jump (Barbell)": "a barbell jump squat, figure with barbell across upper back, performing a dynamic squat and jumping upward",
  "Leg Extension": "a leg extension on a machine, figure seated with legs curled under the pad, extending both legs outward to horizontal",
  "Leg Extension (Machine)": "a leg extension machine exercise, figure seated, lower legs under padded roller, extending legs outward to full extension",
  "Lunge": "a forward lunge, figure stepping one leg forward and bending both knees, back knee nearly touching the floor",
  "Lunge (Barbell)": "a barbell lunge, barbell across upper back, figure stepping forward and lowering back knee toward floor",
  "Lunge (Dumbbell)": "a dumbbell lunge, holding dumbbells at sides, stepping forward and lowering back knee toward floor",
  "Walking Lunge": "a walking lunge, figure stepping forward alternating legs, lowering back knee toward floor with each step",
  "Barbell Lunge": "a barbell lunge with barbell across upper back, stepping forward alternating legs, back knee dropping toward floor",
  "Reverse Lunge": "a reverse lunge, figure stepping one leg backward and lowering back knee toward floor while keeping front foot planted",
  "Lateral Lunge": "a lateral lunge, figure stepping one leg wide to the side, bending the stepping knee while keeping the other leg straight",
  "Curtsy Lunge (Dumbbell)": "a curtsy lunge holding dumbbells, figure stepping one leg diagonally behind the other in a curtsy position, bending both knees",
  "Overhead Dumbbell Lunge": "an overhead dumbbell lunge, figure holding dumbbells overhead with locked arms, stepping forward into a lunge",
  "Jumping Lunge": "a jumping lunge, figure in a split stance jumping explosively and switching legs in the air",
  "Bulgarian Split Squat": "a Bulgarian split squat, figure with rear foot elevated on a bench behind them, front leg performing a single-leg squat",
  "Bulgarian Split Squat (Smith Machine)": "a Bulgarian split squat in a Smith machine, figure with rear foot elevated on a bench, front leg performing squat under fixed bar",
  "Pistol Squat": "a pistol squat, figure balancing on one leg performing a single-leg squat to full depth, other leg extended straight forward",
  "Assisted Pistol Squats": "an assisted pistol squat, figure holding a pole or TRX strap for balance, performing a single-leg squat to full depth",
  "Belt Squat (Machine)": "a belt squat on a machine, figure wearing a hip belt attached to the machine, performing a squat with weight at hips not shoulders",
  "Step Up (Barbell)": "a barbell step-up, figure with barbell across upper back, stepping one foot onto a box or bench and driving up",
  "Dumbbell Step Up": "a dumbbell step-up, figure holding dumbbells at sides, stepping one foot onto a bench and driving the body upward",
  "Lateral Box Jump": "a lateral box jump, figure jumping sideways onto a box, landing softly with both feet on the box",
  "Box Jump": "a box jump, figure jumping forward and landing with both feet on top of a plyo box",

  // LEGS - HAMSTRINGS
  "Leg Curl": "a lying leg curl on a machine, figure lying face down with legs under a padded roller, curling lower legs up toward glutes",
  "Lying Leg Curl (Machine)": "a lying leg curl machine, figure prone with lower legs under roller pad, curling legs toward glutes",
  "Seated Leg Curl (Machine)": "a seated leg curl machine, figure seated upright with legs extended under a pad, curling legs under the seat",
  "Romanian Deadlift": "a Romanian deadlift with a barbell, figure standing with slight knee bend, hingeing at the hips, bar staying close to the legs",
  "Romanian Deadlift (Barbell)": "a barbell Romanian deadlift, figure standing, barbell in hands, hip hinge with slight knee bend, bar close to shins",
  "Romanian Deadlift (Dumbbell)": "a dumbbell Romanian deadlift, figure standing, dumbbells in hands, hip hinge with slight knee bend",
  "Romanian Deadlift Single Leg": "a single-leg Romanian deadlift, figure balancing on one leg, hinging forward with the other leg extending behind for balance",
  "Nordic Hamstring Curl": "a Nordic hamstring curl, figure kneeling with ankles anchored, body lowering forward from kneeling position using hamstring eccentric control",
  "Stiff Leg Deadlift (Barbell)": "a stiff-leg deadlift with a barbell, figure standing with straight or very slightly bent legs, hinging at hips to lower bar",
  "Sumo Deadlift": "a sumo deadlift, figure standing with a very wide stance and toes pointed outward, hands inside the legs gripping the barbell",
  "Glute Ham Raise": "a glute ham raise on a GHD machine, figure with feet locked in, lowering torso forward and curling back up using hamstrings",

  // LEGS - GLUTES
  "Hip Thrust": "a barbell hip thrust, upper back resting on a bench, barbell placed across the hips, feet on floor, driving hips upward to full extension",
  "Hip Thrust (Barbell)": "a barbell hip thrust, upper back on bench, barbell over hip crease, feet flat, hips driving upward with glutes contracted",
  "Hip Thrust (Machine)": "a hip thrust on a dedicated hip thrust machine, figure seated with back against pad, hips thrust forward against resistance",
  "Hip Thrust (Smith Machine)": "a Smith machine hip thrust, upper back on bench, Smith machine bar across hips, driving hips upward",
  "Single Leg Hip Thrust": "a single-leg hip thrust, upper back on bench, one foot on floor, other leg extended, driving one-sided hip thrust upward",
  "Glute Bridge": "a glute bridge lying on the floor, feet flat, arms at sides, driving hips upward until body is in a straight line from shoulders to knees",
  "Single Leg Glute Bridge": "a single-leg glute bridge on the floor, one foot flat, other leg extended, driving hips upward targeting the glute on the planted side",
  "Cable Pull Through": "a cable pull-through, figure standing facing away from a cable with a rope between legs, hinging forward and driving hips back to standing",
  "Cable Kickback": "a cable glute kickback, figure standing at a cable machine with ankle attachment, one leg kicking straight back against cable resistance",
  "Glute Kickback on Floor": "a glute kickback on hands and knees on the floor, one leg kicking backward and upward with foot flexed",
  "Fire Hydrant": "a fire hydrant exercise on hands and knees, one leg raising out to the side like a dog at a hydrant, hip abduction",
  "Clamshell": "a clamshell exercise lying on the side, hips and knees bent at 90 degrees, top knee raising while feet remain together",
  "Frog Pumps (Dumbbell)": "a frog pump lying on the back with soles of feet pressed together in a butterfly position, hips thrusting upward with glutes contracted, dumbbell on hips",
  "Hip Abduction (Machine)": "a hip abduction machine, figure seated, legs pushing outward against padded resistance away from the center",
  "Hip Adduction (Machine)": "a hip adduction machine, figure seated, legs squeezing inward against padded resistance toward the center",
  "Abductor Machine": "a hip abduction machine exercise, figure seated on a machine, legs pushing outward to the sides",
  "Adductor Machine": "a hip adduction machine exercise, figure seated on a machine, legs squeezing together inward",
  "Lateral Band Walk": "a lateral band walk, figure with a resistance band around thighs or ankles, stepping sideways in a squat position",
  "Bird Dog": "a bird dog on hands and knees, extending the opposite arm and leg simultaneously until both are parallel to the floor",

  // CALVES
  "Standing Calf Raise": "a standing calf raise, figure standing on the edge of a step with only the balls of the feet, heels raised as high as possible",
  "Standing Calf Raise (Bodyweight)": "a bodyweight standing calf raise, figure standing on the balls of feet at a step edge, heels raised to full plantar flexion",
  "Standing Calf Raise (Machine)": "a standing calf raise machine, figure with shoulders under padded yoke, heels raised on a calf block",
  "Seated Calf Raise": "a seated calf raise machine, figure seated with knees bent at 90 degrees under a padded bar, raising heels by extending ankles",
  "Seated Calf Raise (Machine)": "a seated calf raise machine, figure with knees bent and a padded bar across thighs, raising heels to work soleus",
  "Donkey Calf Raise": "a donkey calf raise, figure bent over with support and a weight on the lower back, heels dropping below and then raising high",
  "Leg Press Calf Raise": "a calf raise on a leg press machine, only the balls of the feet on the lower part of the platform, extending ankles to work calves",
  "Calf Extension (Machine)": "a calf extension on a machine, figure seated, pressing the forefoot portion of the platform away by extending the ankle",
  "Calf Press (Machine)": "a calf press machine with the figure seated, pressing a platform away using ankle plantar flexion only",
  "Single Leg Calf Raise": "a single-leg calf raise, figure balancing on one foot on the edge of a step, raising up onto tiptoe",
  "Leg Press Calf Raise": "a leg press calf raise, figure on a leg press machine with only the forefoot on the lower portion of the platform, pushing by extending ankles",

  // CORE
  "Plank": "a standard plank, figure in a prone position supported on forearms and toes, body perfectly straight from head to heels",
  "Side Plank": "a side plank, figure lying on their side supported on one forearm and the side of one foot, body in a straight diagonal line",
  "Plank Hip Dips": "a plank hip dip, figure in a standard plank position, rotating hips down to one side and then the other alternately",
  "Cable Crunch": "a kneeling cable crunch, figure kneeling at a cable machine with a rope attachment above, crunching torso downward toward knees",
  "Russian Twist": "a Russian twist, figure seated on the floor with knees bent and feet raised, rotating a weight from side to side",
  "Hanging Leg Raise": "a hanging leg raise, figure hanging from a pull-up bar, legs raised straight to horizontal or higher, targeting lower abs",
  "Toes to Bar": "a toes-to-bar exercise, figure hanging from a pull-up bar, bringing straight legs all the way up to touch the bar",
  "Hanging Knee Raise": "a hanging knee raise, figure hanging from a pull-up bar, knees tucked and raised toward chest",
  "Knee Raise Parallel Bars": "a knee raise on parallel bars, figure supported on forearms between bars, knees raised toward chest",
  "Leg Raise Parallel Bars": "a straight leg raise on parallel bars, figure supported on forearms, raising straight legs to horizontal",
  "Ab Rollout": "an ab wheel rollout, figure kneeling holding an ab wheel, rolling it forward until body is nearly horizontal then pulling back",
  "Ab Wheel": "an ab wheel rollout, figure kneeling with an ab wheel, extending outward until nearly flat and pulling back with core",
  "Cable Core Palloff Press": "a Pallof press with a cable machine to the side, figure standing sideways to the cable, pressing handles straight forward and returning",
  "Pallof Press": "a Pallof press with a cable machine to the side, figure standing sideways, arms extended straight forward holding a handle, resisting rotation",
  "Hollow Body Hold": "a hollow body hold lying on the back, arms and legs extended slightly off the floor, lower back pressed flat, core braced",
  "Hollow Rock": "a hollow rock, figure in a hollow body position rocking back and forth while maintaining the same body shape",
  "Dragon Flag": "a dragon flag on a flat bench, figure gripping behind the head, entire body raised stiff and lowering in one straight unit from shoulder blades",
  "Dragonfly": "a dragonfly exercise on a flat bench, figure gripping behind head, full body raised and slowly lowered like a dragon flag",
  "Dead Bug": "a dead bug exercise lying on the back, arms extended upward, one arm lowering overhead as the opposite leg extends, alternating",
  "Ab Scissors": "an ab scissors exercise lying on back, both legs raised and crossing one over the other in a scissoring motion",
  "Flutter Kicks": "flutter kicks lying on back, both legs slightly raised off the floor, alternately kicking up and down in small rapid motions",
  "Heel Taps": "heel tap crunches, figure lying on back with legs bent, laterally crunching to tap each heel alternately",
  "Bicycle Crunch Raised Legs": "a bicycle crunch with legs raised, figure lying on back, legs in the air, alternating elbow to opposite knee rotations",
  "Decline Crunch": "a decline crunch on a decline bench, figure lying with head lower than hips, crunching torso toward knees",
  "Crunch": "a standard crunch, figure lying on back with knees bent, curling upper body upward to engage abs",
  "Crunch (Machine)": "a crunch at a machine, figure seated, crunching torso forward against machine resistance",
  "Crunch (Weighted)": "a weighted crunch lying on the floor, figure holding a weight plate at chest, performing a full crunch",
  "Decline Crunch (Weighted)": "a weighted decline crunch on a decline bench, holding a weight plate, crunching upper body toward knees",
  "Sit Up": "a sit-up, figure lying on back with feet anchored, raising entire torso upward to an upright seated position",
  "Jackknife Sit Up": "a jackknife sit-up, figure lying flat, simultaneously raising straight legs and upper body to meet in the middle",
  "V-Up": "a V-up exercise, figure lying flat, simultaneously raising both straight legs and upper body to form a V shape",
  "Elbow to Knee": "an elbow-to-knee crunch, figure lying on back alternating bringing elbow toward opposite knee in a bicycle-like motion",
  "Oblique Crunch": "an oblique crunch lying on the side or twisted, one elbow reaching toward the same-side hip to target obliques",
  "Lying Knee Raise": "a lying knee raise, figure lying flat on back, pulling both knees toward chest using lower abs",
  "Lying Leg Raise": "a lying leg raise, figure lying flat on back, raising straight legs from the floor to vertical position",
  "Lateral Leg Raises": "a lateral leg raise lying on the side, one leg raised sideways upward, targeting the hip abductor",
  "Leg Raise": "a hanging or lying leg raise, figure raising legs from a hanging bar or floor position to work lower abs",
  "Mountain Climber": "mountain climbers in a push-up position, alternating driving knees toward chest rapidly",
  "Ball Slams": "a medicine ball slam, figure raising a medicine ball overhead then explosively slamming it down to the floor",
  "Medicine Ball Slam": "a medicine ball slam, figure holding a medicine ball overhead and slamming it forcefully to the floor",
  "Jack Knife (Suspension)": "a jackknife with a suspension trainer, figure in push-up position with feet in TRX straps, pulling knees toward chest",
  "Landmine Squat and Press": "a landmine squat-to-press, figure performing a squat with the landmine bar at shoulder, then pressing it upward as they stand",
  "Cable Twist (Down to up)": "a cable twist from low to high, figure standing side-on to a low cable, rotating torso and pulling handle upward in a diagonal arc",
  "Cable Twist (Up to down)": "a cable twist from high to low, figure standing side-on to a high cable, pulling handle diagonally downward across the body",

  // FOREARMS
  "Wrist Curl": "a wrist curl with a dumbbell seated, forearm resting on thigh, wrist curling upward to fully flex the forearm flexors",
  "Wrist Curl (Barbell)": "a barbell wrist curl seated, forearms resting on thighs, wrists curling upward holding barbell with underhand grip",
  "Wrist Curl (Dumbbell)": "a dumbbell wrist curl seated, forearm on thigh, wrist curling upward then lowering",
  "Wrist Extension (Dumbbell)": "a wrist extension with a dumbbell, forearm resting palm-down on thigh, wrist raising the back of the hand upward",
  "Plate Pinch": "a plate pinch, figure pinching the flat side of two weight plates together between fingers and thumb, holding at arm's length",
  "Farmer Carry": "a farmer carry, figure walking while holding heavy dumbbells or handles at sides, upright posture, strong grip",
  "Farmers Walk": "a farmer's walk, figure walking with heavy dumbbells in each hand at sides, maintaining upright posture",
  "Dead Hang": "a dead hang from a pull-up bar, figure hanging with arms fully extended and hands gripping the bar",

  // COMPOUND / OLYMPIC
  "Deadlift": "a conventional barbell deadlift, figure bending to grip a barbell with standard shoulder-width stance, lifting from floor to lockout",
  "Deadlift (Barbell)": "a conventional barbell deadlift, figure gripping barbell on the floor with standard stance, pulling to a standing lockout",
  "Deadlift (Dumbbell)": "a dumbbell deadlift, figure bending to grip dumbbells at sides off the floor, pulling to standing",
  "Deadlift (Band)": "a resistance band deadlift, figure standing on a band, hinging to grip handles and pulling to standing",
  "Deadlift (Smith Machine)": "a Smith machine deadlift, figure gripping the bar in a fixed track, pulling from floor to standing lockout",
  "Deadlift (Trap bar)": "a trap bar hex bar deadlift, figure inside the hexagonal bar, gripping handles at sides, pulling to standing",
  "Deadlift High Pull": "a deadlift high pull, figure pulling barbell from the floor to an explosive high pull, bar reaching chin height with elbows high",
  "Power Clean": "a power clean, figure catching a barbell in a partial squat with the bar in a front rack position, caught above parallel",
  "Clean": "a barbell clean, figure catching the barbell in a front rack position at shoulder height after an explosive pull from the floor",
  "Clean and Jerk": "a clean and jerk, figure in the catch of the jerk phase with barbell locked overhead in a split stance",
  "Clean Pull": "a clean pull, figure performing the explosive pull phase of a clean, bar at hip height with full triple extension",
  "Hang Clean": "a hang clean, figure starting from standing position with bar at hips, explosive hip extension and high pull, catching in front rack",
  "Kettlebell Swing": "a kettlebell swing, figure in a hinged position swinging a kettlebell between the legs, then driving hips forward to swing it to shoulder height",
  "Kettlebell Clean": "a kettlebell clean, figure swinging a kettlebell from a hinge to a rack position at shoulder with one arm",
  "Kettlebell Turkish Get Up": "a kettlebell Turkish get-up, figure lying on the floor with one arm extended holding a kettlebell overhead, beginning to rise",
  "Push Press": "a push press with a barbell, figure dipping knees slightly then explosively pressing the bar overhead using leg drive",
  "Kettlebell Around the World": "a kettlebell around the world, figure passing a kettlebell around the body in a circle from hand to hand",
  "Sled Push": "a sled push, figure leaning forward with arms extended on a weighted sled, driving it forward with powerful leg strides",
  "Tire Flip": "a tire flip, figure squatting down to grip a large tire, explosively lifting and flipping it forward",
  "Battle Ropes": "battle ropes exercise, figure standing in an athletic stance, both arms alternately slamming two thick ropes in wave motions",
  "Burpees": "a burpee, figure showing the sequence: standing, then dropping to push-up position, performing a push-up, jumping back to standing",
  "Burpee Over the Bar": "a burpee over the bar, figure performing a burpee and then jumping laterally over a barbell on the floor",
  "Wall Ball": "a wall ball exercise, figure performing a squat holding a medicine ball, then throwing it upward to hit a target on the wall",
  "Box Jump": "a box jump, figure jumping from the floor with both feet and landing on top of a plyometric box",
  "Lateral Box Jump": "a lateral box jump, figure jumping sideways from the floor to land on top of a box",
  "Frog Jumps": "frog jumps, figure in a deep squat position jumping explosively forward landing back in a squat",
  "High Knees": "high knees, figure running in place, alternately driving knees upward toward the chest as high as possible",
  "High Knee Skips": "high knee skips, figure performing an exaggerated skipping motion, driving one knee high while pushing off the other foot",
  "Jumping Jack": "a jumping jack, figure with arms raised and legs spread simultaneously, then returning to start position",
  "Jump Rope": "jump rope exercise, figure skipping a jump rope, feet together, wrists rotating the rope",
  "Elliptical Trainer": "an elliptical trainer, figure on an elliptical machine with arms and legs working in an oval stride motion",
  "Cycling": "stationary cycling, figure seated on a stationary bike, legs pedaling in a circular motion",
  "Running": "a running stride, figure in mid-run with one knee raised, arms bent and pumping",
  "Rowing Machine": "a rowing machine exercise, figure in the drive phase, legs straight, body leaning back, arms pulling handle to lower chest",
  "Climbing": "a rock climbing motion, figure on a wall gripping holds with hands and feet, reaching upward",
  "Hiking": "a hiking stride, figure on an incline terrain, stepping forward with trekking poles",
  "Swimming": "a freestyle swimming stroke, figure in the water with one arm extended forward and one pulling back through the water",
  "HIIT": "a HIIT training session with a figure performing a dynamic jumping or cardio movement at high intensity",

  // SPECIAL
  "Handstand Hold": "a handstand hold against a wall, figure inverted with arms locked, body straight and feet against wall",
  "Front Lever Hold": "a front lever hold on a bar, figure hanging horizontally from a bar with body completely parallel to the floor",
  "Front Lever Raise": "a front lever raise, figure starting in a dead hang and raising the entire body to a horizontal front lever position",
  "L-Sit Hold": "an L-sit hold, figure supported on parallel bars or dips with legs raised horizontally in front forming an L shape",
  "Muscle Up": "a muscle-up on a bar, figure starting from a hanging pull-up and transitioning above the bar to a dip lockout",
  "Ring Muscle Up": "a ring muscle-up on gymnastic rings, figure transitioning from a ring pull-up to above the rings in a ring dip position",
  "Ring Pull Up": "a ring pull-up, figure hanging from gymnastic rings with straight arms, pulling up until chin is above hands",
  "Ring Push Up": "a ring push-up, figure in push-up position with hands in gymnastic rings, performing a push-up with rings slightly flared",
  "Dumbbell Pullover": "a dumbbell pullover lying across a flat bench with only shoulders on the bench, hips dropped, single dumbbell lowered behind head in an arc",
  "Rope Climb": "a rope climb, figure gripping a thick vertical rope overhead, using arms and legs to ascend the rope",
  "Landmine Squat and Press": "a landmine squat and press, figure squatting with landmine at shoulder then pressing it overhead as they stand",
  "Snatch (Barbell)": "a full barbell snatch in the catch position, figure sitting in a squat with barbell locked overhead in a wide grip",
  "Power Snatch": "a power snatch, barbell caught overhead in a partial squat, wide grip, arms locked overhead",
  "Thruster (Barbell)": "a barbell thruster, barbell starting in front rack, figure squatting then pressing overhead in one fluid movement",
  "Clean and Jerk": "a barbell clean and jerk, figure in the split jerk catch position, barbell locked overhead, feet split fore and aft",
  "Downward Dog": "a downward dog yoga pose, figure in an inverted V shape with hands and feet on the floor, hips raised high",
  "Yoga Flow": "a yoga flow sequence, figure performing a smooth transition between yoga poses such as warrior and downward dog",
  "Toe Touch": "a standing toe touch, figure bending forward with straight legs to reach hands toward or past the toes",
  "Hollow Rock": "a hollow rock, figure rocking in a hollowed body position, arms and legs extended and slightly off the floor",
  "Bicycle Crunch Raised Legs": "a bicycle crunch, lying on back, legs in the air, elbows and opposite knees alternating toward each other",
  "Chest Supported Y Raise (Dumbbell)": "a Y raise face down on an incline bench, arms raising in a Y shape diagonally upward, targeting lower traps",
  "Meadows Row": "a Meadows row using a landmine setup, figure in a staggered stance, single arm pulling the sleeve end of the bar toward the hip",
  "Inverted Row": "an inverted row under a fixed bar, figure hanging with straight body pulling chest up to the bar from below",
  "Dragon Flag": "a dragon flag on a flat bench, figure gripping behind the head, body forming a stiff straight line from shoulders down, raised and lowered as one unit",
  "Frog Pumps (Dumbbell)": "a frog pump lying on the back, soles of feet together in a butterfly position, hips thrusting upward with a dumbbell balanced on hips",
  "Low Row (Suspension)": "a TRX suspension low row, figure leaning backward holding handles, pulling the body up by bending elbows",
  "Rack Pull": "a rack pull from knee height in a power rack, figure pulling a loaded barbell from pin-level to a standing lockout",
  "Nordic Hamstring Curl": "a Nordic hamstring curl kneeling, ankles secured under a bar or pad, figure lowering the torso forward using eccentric hamstring control",
  "Glute Ham Raise": "a glute ham raise on a GHD machine, figure with ankles hooked, lowering torso and curling back up with hamstrings and glutes",
  "Around The World": "an around-the-world with a plate or dumbbell, figure passing the weight in a circular arc around the body or head",
  "Squat (Band)": "a resistance band squat, figure standing on band with handles at shoulders, squatting down and driving back up",
  "Assisted Pistol Squats": "an assisted pistol squat using a TRX or post, figure lowering on one leg to full depth while holding support",
  "Lateral Band Walk": "a lateral band walk, mini band around thighs or ankles, figure in a squat position stepping sideways",
  "Hip Abduction (Machine)": "a hip abduction machine, seated with thighs against pads, legs opening outward against resistance",
  "Hip Adduction (Machine)": "a hip adduction machine, seated with pads on inner thighs, legs squeezing together inward",
  "Clamshell": "a clamshell, lying on the side with hips and knees bent, rotating the top knee upward while keeping feet together",
  "Fire Hydrant": "a fire hydrant, on hands and knees, one knee lifting out to the side like a dog raising its leg",
  "Lateral Leg Raises": "a lateral leg raise, lying on side, top leg raising upward and returning down",
  "Burpee Over the Bar": "a burpee over a barbell, dropping to push-up position, then jumping laterally over the bar on the floor",
  "Clean Pull": "a clean pull with barbell, explosive triple extension with bar at hip height, traps shrugging, elbows high",
  "Leg Raise Parallel Bars": "a hanging leg raise on parallel bars, figure suspended with forearms, raising straight legs to horizontal",
  "Gorilla Row (Kettlebell)": "a gorilla row, figure straddling two kettlebells on the floor in a bent-over position, alternately rowing each kettlebell",
  "Good Morning (Barbell)": "a barbell good morning, bar across upper back, figure hinging at hips with a slight knee bend until torso is near parallel",
  "Chest Supported Incline Row (Dumbbell)": "a chest-supported row, figure face down on an incline bench, rowing two dumbbells toward the hips simultaneously",
  "Kettlebell High Pull": "a kettlebell high pull, figure swinging a kettlebell from below the knees and pulling it up to chin height with elbows high",
  "Landmine Row": "a landmine row, figure in a bent-over position, gripping the end of a landmine bar, rowing it toward the hip",
  "Iso-Lateral High Row (Machine)": "an iso-lateral high row on a machine, each arm independently pulling a handle from high to hip in a rowing motion",
  "Hang Snatch": "a hang snatch, figure starting from standing with bar at mid-thigh, explosively pulling and punching bar overhead",
  "Dumbbell Snatch": "a dumbbell snatch, figure starting in a hinged position, explosively pulling a dumbbell from below to a locked overhead position in one motion",
  "Kettlebell Turkish Get Up": "a Turkish get-up, figure transitioning from lying on the floor to standing while keeping a kettlebell locked overhead throughout",
  "Boxing": "a boxing stance with punching motion, figure in a fighting stance throwing a straight punch or jab combination",
  "Rope Climb": "a rope climb, figure with hands wrapped around a thick rope overhead, actively climbing upward using pulling strength",
  "Kipping Pull Up": "a kipping pull-up, figure using swinging hip momentum to assist explosive pull-up movement above the bar",
  "Muscle Up": "a bar muscle-up, figure starting from a hanging position and explosively transitioning over the bar to dip lockout",
  "Power Clean": "a power clean, figure catching a barbell in a partial squat at shoulder height in a front rack position",
  "Clean and Jerk": "a barbell clean and jerk, figure pressing barbell overhead in a split position with arms fully locked out",
  "Chest Fly (Suspension)": "a suspension trainer chest fly, figure leaning forward holding TRX handles wide apart, arms extended, returning to center",
  "Push Up (Suspension)": "a suspension push-up, figure with hands in TRX rings performing a push-up, rings adding instability",
  "Drag Curl": "a drag curl with a barbell, figure curling the bar while dragging it up along the torso with elbows moving behind the body",
  "21s Bicep Curl": "a 21s bicep curl variation showing a figure performing half reps on a barbell curl, split into lower half and upper half ranges",
  "Zottman Curl": "a Zottman curl, dumbbells curled up with supinated palms, rotated to pronated at the top, then lowered slowly",
  "Bicycle Crunch Raised Legs": "a bicycle crunch with legs raised and alternating elbow-to-knee rotation, targeting obliques and lower abs",
};

// The prompt template
function buildPrompt(exerciseName) {
  const description = EXERCISE_DESCRIPTIONS[exerciseName] || `a ${exerciseName} exercise`;
  return `Anatomical line-art illustration of a human figure performing ${description}. White background. Primary muscles highlighted in soft purple-blue fill. Secondary muscles as lighter outline. Black outlines only on the figure. Clean, professional, fitness encyclopedia style. No text, no labels, no annotations, no watermarks. Side view or three-quarter view. No background environment.`;
}

// Exercises that commonly get wrong images — highest priority to regenerate
const HIGH_PRIORITY = new Set([
  "Hack Squat", "Hack Squat (Machine)", "Front Squat", "Front Squat (Barbell)",
  "Box Squat (Barbell)", "Sumo Deadlift", "Bulgarian Split Squat", "Bulgarian Split Squat (Smith Machine)",
  "Romanian Deadlift", "Romanian Deadlift (Barbell)", "Romanian Deadlift (Dumbbell)",
  "Nordic Hamstring Curl", "Nordic Hamstring Curl",
  "Bayesian Curl", "Spider Curl", "Incline Dumbbell Curl", "Concentration Curl",
  "Preacher Curl", "Preacher Curl (Barbell)", "Preacher Curl (Dumbbell)",
  "Reverse Curl", "Reverse Curl (Barbell)", "Reverse Curl (Cable)",
  "Hammer Curl", "Hammer Curl (Dumbbell)",
  "Cable Crunch", "Pallof Press", "Cable Core Palloff Press", "Dragon Flag", "Dragonfly",
  "Hollow Body Hold", "Ab Rollout", "Ab Wheel", "Toes to Bar",
  "Hip Thrust", "Hip Thrust (Barbell)", "Single Leg Hip Thrust",
  "Cable Pull Through", "Frog Pumps (Dumbbell)",
  "Arnold Press", "Arnold Press (Dumbbell)", "Face Pull",
  "Skull Crusher", "Skull Crusher (EZ Bar)", "Skull Crusher (Dumbbell)",
  "Overhead Tricep Extension", "Overhead Tricep Extension (Dumbbell)",
  "Tricep Pushdown", "Tricep Pushdown (Cable Bar)", "Tricep Pushdown (Cable Rope)",
  "Dumbbell Kickback", "Tricep Kickback (Dumbbell)",
  "Incline Bench Press", "Incline Bench Press (Barbell)",
  "Decline Bench Press", "Decline Bench Press (Barbell)",
  "Dumbbell Chest Press", "Bench Press (Dumbbell)",
  "Seated Cable Row", "T-Bar Row", "Meadows Row",
  "Upright Row", "Upright Row (Barbell)", "Lateral Raise", "Lateral Raise (Dumbbell)",
  "Rear Delt Fly", "Rear Delt Fly (Dumbbell)",
  "Goblet Squat", "Kettlebell Goblet Squat",
  "Standing Calf Raise", "Seated Calf Raise", "Donkey Calf Raise",
  "Leg Press Calf Raise", "Leg Extension", "Leg Extension (Machine)",
  "Lying Leg Curl (Machine)", "Seated Leg Curl (Machine)",
  "Glute Bridge", "Single Leg Glute Bridge",
  "Bird Dog", "Plank", "Dead Bug",
]);

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    const { mode = 'audit', batch_size = 5, offset = 0, target = 'priority' } = await req.json().catch(() => ({}));

    const db = base44.asServiceRole;
    const exercises = await db.entities.Exercise.list('-created_date', 2000);

    if (mode === 'audit') {
      // Just audit - check which exercises have descriptions available
      // Sample first exercise to understand structure
      const sample = exercises[0];
      const sampleName = sample?.name || sample?.data?.name;
      
      const withDescriptions = [];
      const withoutDescriptions = [];
      for (const ex of exercises) {
        const name = ex?.name || ex?.data?.name;
        if (EXERCISE_DESCRIPTIONS[name]) {
          withDescriptions.push(name);
        } else {
          withoutDescriptions.push(name);
        }
      }
      return Response.json({
        total: exercises.length,
        covered: withDescriptions.length,
        sample_exercise: sample,
        sample_name: sampleName,
        not_covered: withoutDescriptions.slice(0, 30),
        high_priority_count: [...HIGH_PRIORITY].filter(n => exercises.some(e => (e?.name || e?.data?.name) === n)).length,
      });
    }

    if (mode === 'regenerate') {
      // Regenerate images for a batch of exercises
      let targets;
      if (target === 'priority') {
        targets = exercises.filter(ex => HIGH_PRIORITY.has(ex?.name || ex?.data?.name));
      } else if (target === 'all') {
        targets = exercises.filter(ex => EXERCISE_DESCRIPTIONS[ex?.name || ex?.data?.name]);
      } else if (target === 'uncovered') {
        targets = exercises.filter(ex => !EXERCISE_DESCRIPTIONS[ex?.name || ex?.data?.name]);
      } else {
        targets = exercises;
      }

      const batch = targets.slice(offset, offset + batch_size);
      const results = [];

      for (const exercise of batch) {
        const name = exercise?.name || exercise?.data?.name;
        const prompt = buildPrompt(name);
        
        try {
          const imgResult = await db.integrations.Core.GenerateImage({ prompt });
          const imageUrl = imgResult.url;
          
          await db.entities.Exercise.update(exercise.id, {
            image_url: imageUrl,
            image_url_dark: imageUrl,
          });
          
          results.push({ name, status: 'updated', url: imageUrl });
        } catch (err) {
          results.push({ name, status: 'error', error: err.message });
        }
      }

      return Response.json({
        mode: 'regenerate',
        target,
        offset,
        batch_size,
        processed: batch.length,
        total_targets: targets.length,
        remaining: Math.max(0, targets.length - offset - batch_size),
        next_offset: offset + batch_size,
        results,
      });
    }

    return Response.json({ error: 'Invalid mode. Use: audit, regenerate' }, { status: 400 });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});