import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

const BASE = "https://media.base44.com/images/public/69b2f15b471168c6ba346b2e/";

const IMAGE_MAP = {
  "Bench Press": BASE + "16807e489_generated_image.png",
  "Squat": BASE + "9e5ca77da_generated_image.png",
  "Deadlift": BASE + "6762f7b90_generated_image.png",
  "Shoulder Press": BASE + "6e185145e_generated_image.png",
  "Barbell Row": BASE + "fdea5753e_generated_image.png",
  "Pull-ups": BASE + "ff35ecc94_generated_image.png",
  "Dumbbell Curl": BASE + "74a19c230_generated_image.png",
  "Tricep Pushdown": BASE + "35110aeb0_generated_image.png",
  "Leg Press": BASE + "98d250601_generated_image.png",
  "Lat Pulldown": BASE + "55bf050d9_generated_image.png",
  "Incline Dumbbell Press": BASE + "6c65cbb98_generated_image.png",
  "Romanian Deadlift": BASE + "fa4dde224_generated_image.png",
  "Plank": BASE + "764005e66_generated_image.png",
  "Cable Fly": BASE + "5c7abec39_generated_image.png",
  "Hip Thrust": BASE + "4096056b7_generated_image.png",
  "Incline Bench Press": BASE + "1a7342b81_generated_image.png",
  "Decline Bench Press": BASE + "963f0d82c_generated_image.png",
  "Dumbbell Chest Press": BASE + "a47e58cc8_generated_image.png",
  "Pec Deck Machine": BASE + "603dc776f_generated_image.png",
  "Push-ups": BASE + "267670441_generated_image.png",
  "Chest Dip": BASE + "f3d8f07ad_generated_image.png",
  "Front Squat": BASE + "8b80d319f_generated_image.png",
  "Leg Curl": BASE + "5635ad279_generated_image.png",
  "Leg Extension": BASE + "a4f7b3259_generated_image.png",
  "Hack Squat": BASE + "e4c2e5358_generated_image.png",
  "Walking Lunge": BASE + "4ebc69835_generated_image.png",
  "Goblet Squat": BASE + "2645aca8d_generated_image.png",
  "Sumo Deadlift": BASE + "6329236d9_generated_image.png",
  "Bulgarian Split Squat": BASE + "94d383144_generated_image.png",
  "Lateral Raise": BASE + "8b07ad3b8_generated_image.png",
  "Front Raise": BASE + "78fad5d9a_generated_image.png",
  "Rear Delt Fly": BASE + "14af457b2_generated_image.png",
  "Face Pull": BASE + "4ca4873c5_generated_image.png",
  "Upright Row": BASE + "aba404865_generated_image.png",
  "Arnold Press": BASE + "722d4ce5e_generated_image.png",
  "Dumbbell Shoulder Press": BASE + "6ebb4a230_generated_image.png",
  "Cable Lateral Raise": BASE + "fa3a1cdd5_generated_image.png",
  "Barbell Curl": BASE + "d5f10c33b_generated_image.png",
  "Hammer Curl": BASE + "02a76ede1_generated_image.png",
  "Cable Curl": BASE + "4e20ed6a6_generated_image.png",
  "Preacher Curl": BASE + "8e038a7fa_generated_image.png",
  "Concentration Curl": BASE + "92e96c5e5_generated_image.png",
  "Incline Dumbbell Curl": BASE + "2ce230d7c_generated_image.png",
  "Spider Curl": BASE + "53a697905_generated_image.png",
  "Bayesian Curl": BASE + "61c2da377_generated_image.png",
  "Tricep Dip": BASE + "db4d820e7_generated_image.png",
  "Close Grip Bench Press": BASE + "db5dd8f45_generated_image.png",
  "Skull Crusher": BASE + "a87b329e9_generated_image.png",
  "Overhead Tricep Extension": BASE + "4803f4e12_generated_image.png",
  "Dumbbell Kickback": BASE + "fa7e6a92f_generated_image.png",
  "Seated Cable Row": BASE + "de839129a_generated_image.png",
  "Single Arm Dumbbell Row": BASE + "c5c07cfe8_generated_image.png",
  "T-Bar Row": BASE + "5eabdedfc_generated_image.png",
  "Machine Row": BASE + "c0fe4b24b_generated_image.png",
  "Hyperextension": BASE + "c13b60b2e_generated_image.png",
  "Machine Shoulder Press": BASE + "d6cd1d1be_generated_image.png",
  "Cable Crunch": BASE + "e7473696a_generated_image.png",
  "Russian Twist": BASE + "686140547_generated_image.png",
  "Decline Crunch": BASE + "e262b0469_generated_image.png",
  "Hanging Leg Raise": BASE + "471ac5809_generated_image.png",
  "Ab Rollout": BASE + "2e6024965_generated_image.png",
  "Side Plank": BASE + "b951cb6e2_generated_image.png",
  "Dead Bug": BASE + "16e026292_generated_image.png",
  "Toes to Bar": BASE + "46ef0c9fe_generated_image.png",
  "Pallof Press": BASE + "9c76be7fe_generated_image.png",
  "Hollow Body Hold": BASE + "a749deae3_generated_image.png",
  "Dragon Flag": BASE + "f8dcfa61c_generated_image.png",
  "Cable Kickback": BASE + "959fb17f6_generated_image.png",
  "Glute Bridge": BASE + "a1233541c_generated_image.png",
  "Single Leg Hip Thrust": BASE + "957787419_generated_image.png",
  "Cable Pull Through": BASE + "688204ae1_generated_image.png",
  "Standing Calf Raise": BASE + "a264ac7e6_generated_image.png",
  "Seated Calf Raise": BASE + "96534fc36_generated_image.png",
  "Donkey Calf Raise": BASE + "8838e7986_generated_image.png",
  "Leg Press Calf Raise": BASE + "78c9b97f9_generated_image.png",
  "Farmer Carry": BASE + "6aa7c0031_generated_image.png",
  "Reverse Curl": BASE + "79a777e46_generated_image.png",
  "Kettlebell Swing": BASE + "f7c8b79bf_generated_image.png",
  "Box Jump": BASE + "3e3368f93_generated_image.png",
  "Burpees": BASE + "90eeaaf58_generated_image.png",
  "Power Clean": BASE + "87943dbc4_generated_image.png",
  "Nordic Hamstring Curl": BASE + "96b317b83_generated_image.png",
  "Sissy Squat": BASE + "524401819_generated_image.png",
  "Meadows Row": BASE + "2fd4e2584_generated_image.png",
  "Wrist Curl": BASE + "9e05135e3_generated_image.png",
  "Single Leg Calf Raise": BASE + "072090255_generated_image.png",
  "Chin-ups": BASE + "4d3a109bd_generated_image.png",
  "Barbell Overhead Press": BASE + "4a9b1d713_generated_image.png",
  "21s Bicep Curl": BASE + "c33da3773_generated_image.png",
  "Ab Scissors": BASE + "f4623e2b0_generated_image.png",
  "Ab Wheel": BASE + "2d677d908_generated_image.png",
  "Abductor Machine": BASE + "f9f2cef7e_generated_image.png",
  "Adductor Machine": BASE + "ebace6c9a_generated_image.png",
  "Arnold Press (Dumbbell)": BASE + "313daddbd_generated_image.png",
  "Around The World": BASE + "039fa07f6_generated_image.png",
  "Assisted Pistol Squats": BASE + "624ada4e5_generated_image.png",
  "Back Extension (Hyperextension)": BASE + "e137aa1d5_generated_image.png",
  "Back Extension (Machine)": BASE + "b9a43a0d3_generated_image.png",
  "Back Extension (Weighted Hyperextension)": BASE + "4bdc638f0_generated_image.png",
  "Ball Slams": BASE + "e5f037834_generated_image.png",
  "Band Pull Apart": BASE + "e1b750c2f_generated_image.png",
  "Barbell Lunge": BASE + "912f14c24_generated_image.png",
  "Barbell Shrug": BASE + "5b113f23c_generated_image.png",
  "Battle Ropes": BASE + "a50b52650_generated_image.png",
  "Behind the Back Bicep Wrist Curl (Barbell)": BASE + "6cae92f9d_generated_image.png",
  "Behind the Back Curl (Cable)": BASE + "f683a07d6_generated_image.png",
  "Belt Squat (Machine)": BASE + "028e6071d_generated_image.png",
  "Bench Dip": BASE + "d2dc7cc87_generated_image.png",
  "Bench Press - Close Grip (Barbell)": BASE + "cac8fc0b7_generated_image.png",
  "Bench Press - Wide Grip (Barbell)": BASE + "94b911015_generated_image.png",
  "Bench Press (Barbell)": BASE + "3d41662ab_generated_image.png",
  "Bench Press (Cable)": BASE + "0c1c78237_generated_image.png",
  "Bench Press (Dumbbell)": BASE + "6d4edd962_generated_image.png",
  "Bench Press (Smith Machine)": BASE + "7fe4891d9_generated_image.png",
  "Bent Over Row (Band)": BASE + "74f2821ff_generated_image.png",
  "Bent Over Row (Barbell)": BASE + "ce97d3e87_generated_image.png",
  "Bent Over Row (Dumbbell)": BASE + "186fd3638_generated_image.png",
  "Bicep Curl (Barbell)": BASE + "5ea8b768c_generated_image.png",
  "Bicep Curl (Cable)": BASE + "e315cd4b2_generated_image.png",
  "Bicep Curl (Dumbbell)": BASE + "9b199964a_generated_image.png",
  "Bicep Curl (Machine)": BASE + "d177045af_generated_image.png",
  "Bicep Curl (Suspension)": BASE + "2dfb5dd24_generated_image.png",
  "Bicycle Crunch Raised Legs": BASE + "9e1ec1dc7_generated_image.png",
  "Bird Dog": BASE + "db06965d4_generated_image.png",
  "Box Squat (Barbell)": BASE + "3ea7efbef_generated_image.png",
  "Boxing": BASE + "e65a2912a_generated_image.png",
  "Bulgarian Split Squat (Smith Machine)": BASE + "024f9ddad_generated_image.png",
  "Burpee Over the Bar": BASE + "fbbed4c67_generated_image.png",
  "Butterfly (Pec Deck)": BASE + "75832b220_generated_image.png",
  "Cable Core Palloff Press": BASE + "022521e11_generated_image.png",
  "Cable Fly Crossovers": BASE + "6067abd37_generated_image.png",
  "Cable Twist (Down to up)": BASE + "101758e6a_generated_image.png",
  "Cable Twist (Up to down)": BASE + "65d11391a_generated_image.png",
  "Calf Extension (Machine)": BASE + "cd25f15e4_generated_image.png",
  "Calf Press (Machine)": BASE + "8d4d0b243_generated_image.png",
  "Chest Dip (Assisted)": BASE + "feba65749_generated_image.png",
  "Chest Dip (Weighted)": BASE + "15506c393_generated_image.png",
  "Chest Fly (Band)": BASE + "1f8336c90_generated_image.png",
  "Chest Fly (Dumbbell)": BASE + "87cabf2ec_generated_image.png",
  "Chest Fly (Machine)": BASE + "d7aba0173_generated_image.png",
  "Chest Fly (Suspension)": BASE + "0f245c05a_generated_image.png",
  "Chest Press (Band)": BASE + "3c7e7a477_generated_image.png",
  "Chest Press (Machine)": BASE + "860570873_generated_image.png",
  "Chest Supported Incline Row (Dumbbell)": BASE + "806d55897_generated_image.png",
  "Chest Supported Reverse Fly (Dumbbell)": BASE + "64caf1c03_generated_image.png",
  "Chest Supported Y Raise (Dumbbell)": BASE + "45ad48a3e_generated_image.png",
  "Chin Up": BASE + "faaf481ad_generated_image.png",
  "Chin Up (Assisted)": BASE + "995cffb77_generated_image.png",
  "Chin Up (Weighted)": BASE + "85e3227bb_generated_image.png",
  "Clamshell": BASE + "5977c6311_generated_image.png",
  "Clap Push Ups": BASE + "f3ffaaed8_generated_image.png",
  "Clean": BASE + "af9fde205_generated_image.png",
  "Clean and Jerk": BASE + "5f8e17f89_generated_image.png",
  "Clean Pull": BASE + "eaac869c7_generated_image.png",
  "Climbing": BASE + "5ca52be88_generated_image.png",
  "Cross Body Hammer Curl": BASE + "e4ff4ecc6_generated_image.png",
  "Crunch": BASE + "1a2c5fa40_generated_image.png",
  "Crunch (Machine)": BASE + "395e53bc4_generated_image.png",
  "Crunch (Weighted)": BASE + "937cfcc22_generated_image.png",
  "Curtsy Lunge (Dumbbell)": BASE + "ced5a2bf2_generated_image.png",
  "Cycling": BASE + "4b9853829_generated_image.png",
  "Dead Hang": BASE + "d73d4e3f1_generated_image.png",
  "Deadlift (Band)": BASE + "f46af69d7_generated_image.png",
  "Deadlift (Barbell)": BASE + "ade19a8f6_generated_image.png",
  "Deadlift (Dumbbell)": BASE + "1c113fa40_generated_image.png",
  "Deadlift (Smith Machine)": BASE + "7c98f68af_generated_image.png",
  "Deadlift (Trap bar)": BASE + "79793a3dd_generated_image.png",
  "Deadlift High Pull": BASE + "55bdfce80_generated_image.png",
  "Decline Bench Press (Barbell)": BASE + "ee49b6502_generated_image.png",
  "Decline Bench Press (Dumbbell)": BASE + "dff8ab019_generated_image.png",
  "Decline Bench Press (Machine)": BASE + "0f7a678df_generated_image.png",
  "Decline Bench Press (Smith Machine)": BASE + "c58599d17_generated_image.png",
  "Decline Chest Fly (Dumbbell)": BASE + "6b22b1f96_generated_image.png",
  "Decline Crunch (Weighted)": BASE + "330cdc7a3_generated_image.png",
  "Decline Push Up": BASE + "0ea6def43_generated_image.png",
  "Diamond Push Up": BASE + "886e098b5_generated_image.png",
  "Drag Curl": BASE + "389d047c9_generated_image.png",
  "Downward Dog": BASE + "0954f9f47_generated_image.png",
  "Dragonfly": BASE + "2ceab8847_generated_image.png",
  "Dumbbell Row": BASE + "dcb59a82a_generated_image.png",
  "Dumbbell Snatch": BASE + "e08f58f6d_generated_image.png",
  "Dumbbell Squeeze Press": BASE + "a7f100c9d_generated_image.png",
  "Dumbbell Step Up": BASE + "ca7bf88bc_generated_image.png",
  "Dumbbell Pullover": BASE + "9eea10626_generated_image.png",
  "Barbell Pullover": BASE + "3b88e157a_generated_image.png",
  "Cable Pullover": BASE + "19182c112_generated_image.png",
  "Elbow to Knee": BASE + "c59dc25c8_generated_image.png",
  "Elliptical Trainer": BASE + "06faa9b49_generated_image.png",
  "EZ Bar Biceps Curl": BASE + "75ea09177_generated_image.png",
  "Farmers Walk": BASE + "22867eb5b_generated_image.png",
  "Feet Up Bench Press (Barbell)": BASE + "096f519fa_generated_image.png",
  "Fire Hydrant": BASE + "66080981c_generated_image.png",
  "Floor Press (Barbell)": BASE + "3a850d0fc_generated_image.png",
  "Floor Press (Dumbbell)": BASE + "fa050d808_generated_image.png",
  "Floor Triceps Dip": BASE + "17895aee9_generated_image.png",
  "Flutter Kicks": BASE + "6dbd442da_generated_image.png",
  "Frog Jumps": BASE + "17e31a266_generated_image.png",
  "Frog Pumps (Dumbbell)": BASE + "b75bf92c4_generated_image.png",
  "Front Lever Hold": BASE + "b4e05b3a6_generated_image.png",
  "Front Lever Raise": BASE + "2adcbd630_generated_image.png",
  "Front Raise (Band)": BASE + "4aa15c365_generated_image.png",
  "Front Raise (Barbell)": BASE + "275b3f2c8_generated_image.png",
  "Front Raise (Cable)": BASE + "2618566a4_generated_image.png",
  "Front Raise (Dumbbell)": BASE + "6ca7f581c_generated_image.png",
  "Front Raise (Suspension)": BASE + "f3f4f2f5a_generated_image.png",
  "Front Squat (Barbell)": BASE + "a57bde778_generated_image.png",
  "Full Squat": BASE + "37332311a_generated_image.png",
  "Glute Ham Raise": BASE + "db5143436_generated_image.png",
  "Glute Kickback on Floor": BASE + "ecc23e2dc_generated_image.png",
  "Good Morning (Barbell)": BASE + "956b04979_generated_image.png",
  "Gorilla Row (Kettlebell)": BASE + "1c1ea2617_generated_image.png",
  "Hack Squat (Machine)": BASE + "bab4a8ea2_generated_image.png",
  "Hammer Curl (Band)": BASE + "951098422_generated_image.png",
  "Hammer Curl (Cable)": BASE + "220bd5d3a_generated_image.png",
  "Hammer Curl (Dumbbell)": BASE + "e99958ed2_generated_image.png",
  "Handstand Hold": BASE + "6b9c770d9_generated_image.png",
  "Hang Clean": BASE + "d9c6a3bd4_generated_image.png",
  "Hang Snatch": BASE + "0a8b33381_generated_image.png",
  "Hanging Knee Raise": BASE + "909cbf7e0_generated_image.png",
  "Heel Taps": BASE + "41557fac7_generated_image.png",
  "Hex Press (Dumbbell)": BASE + "f584e988e_generated_image.png",
  "High Knee Skips": BASE + "0d03404de_generated_image.png",
  "High Knees": BASE + "9a3f3f055_generated_image.png",
  "HIIT": BASE + "abe4ccc38_generated_image.png",
  "Hiking": BASE + "1d875f155_generated_image.png",
  "Hip Abduction (Machine)": BASE + "e9f9c0657_generated_image.png",
  "Hip Adduction (Machine)": BASE + "fd2558b47_generated_image.png",
  "Hip Thrust (Barbell)": BASE + "4e654df0c_generated_image.png",
  "Hip Thrust (Machine)": BASE + "c3e20cde1_generated_image.png",
  "Hip Thrust (Smith Machine)": BASE + "7d86c5331_generated_image.png",
  "Hollow Rock": BASE + "a9c8e395a_generated_image.png",
  "Incline Bench Press (Barbell)": BASE + "5a5b34469_generated_image.png",
  "Incline Bench Press (Smith Machine)": BASE + "e5f9ecabb_generated_image.png",
  "Incline Chest Fly (Dumbbell)": BASE + "b8d4f54fd_generated_image.png",
  "Incline Chest Press (Machine)": BASE + "9bf082124_generated_image.png",
  "Incline Push Ups": BASE + "f6b1acada_generated_image.png",
  "Inverted Row": BASE + "e9916c7a0_generated_image.png",
  "Iso-Lateral Chest Press (Machine)": BASE + "306faad3c_generated_image.png",
  "Iso-Lateral High Row (Machine)": BASE + "3e5ca530f_generated_image.png",
  "Iso-Lateral Low Row": BASE + "cea807a5e_generated_image.png",
  "Iso-Lateral Row (Machine)": BASE + "dca4ea426_generated_image.png",
  "Jack Knife (Suspension)": BASE + "cf18ee454_generated_image.png",
  "Jackknife Sit Up": BASE + "4d878e518_generated_image.png",
  "JM Press (Barbell)": BASE + "96b24dbbc_generated_image.png",
  "Jump Rope": BASE + "89b58abfe_generated_image.png",
  "Jump Squat": BASE + "7028c3f74_generated_image.png",
  "Jumping Jack": BASE + "f5eeca183_generated_image.png",
  "Jumping Lunge": BASE + "d8580908c_generated_image.png",
  "Kettlebell Around the World": BASE + "8cc8ef929_generated_image.png",
  "Kettlebell Clean": BASE + "b73096f32_generated_image.png",
  "Kettlebell Curl": BASE + "45dca76ff_generated_image.png",
  "Kettlebell Goblet Squat": BASE + "a79503a7c_generated_image.png",
  "Kettlebell Halo": BASE + "713318e15_generated_image.png",
  "Kettlebell High Pull": BASE + "f024f39df_generated_image.png",
  "Kettlebell Press": BASE + "b425051aa_generated_image.png",
  "Kettlebell Shoulder Press": BASE + "751880c4c_generated_image.png",
  "Kettlebell Snatch": BASE + "c5cf08c97_generated_image.png",
  "Kettlebell Turkish Get Up": BASE + "068957f25_generated_image.png",
  "Kipping Pull Up": BASE + "313ece6f9_generated_image.png",
  "Knee Raise Parallel Bars": BASE + "72681a93e_generated_image.png",
  "Kneeling Pulldown (Band)": BASE + "8856e82f3_generated_image.png",
  "Kneeling Push Up": BASE + "479b969e6_generated_image.png",
  "L-Sit Hold": BASE + "08d2162bf_generated_image.png",
  "Landmine 180": BASE + "3798a12d8_generated_image.png",
  "Landmine Press": BASE + "0397a684b_generated_image.png",
  "Landmine Row": BASE + "22d5b868b_generated_image.png",
  "Landmine Squat and Press": BASE + "fd5debc43_generated_image.png",
  "Lateral Band Walk": BASE + "c9efa658d_generated_image.png",
  "Lateral Box Jump": BASE + "cc5eda133_generated_image.png",
  "Lateral Leg Raises": BASE + "0f014f09f_generated_image.png",
  "Lateral Lunge": BASE + "6c659e451_generated_image.png",
  "Lateral Raise (Band)": BASE + "011176488_generated_image.png",
  "Lateral Raise (Cable)": BASE + "ca848c4ea_generated_image.png",
  "Lateral Raise (Dumbbell)": BASE + "e8890081d_generated_image.png",
  "Lateral Raise (Machine)": BASE + "60ddd511d_generated_image.png",
  "Lateral Squat": BASE + "3894c2132_generated_image.png",
  "Lat Pulldown - Close Grip (Cable)": BASE + "7e33693bd_generated_image.png",
  "Lat Pulldown (Band)": BASE + "72eee8f0f_generated_image.png",
  "Lat Pulldown (Cable)": BASE + "94550cbb2_generated_image.png",
  "Lat Pulldown (Machine)": BASE + "198ea6413_generated_image.png",
  "Leg Extension (Machine)": BASE + "6be3f95a8_generated_image.png",
  "Leg Press (Machine)": BASE + "4f169b17b_generated_image.png",
  "Leg Press Horizontal (Machine)": BASE + "8e1436ccd_generated_image.png",
  "Leg Raise": BASE + "d5f568bd7_generated_image.png",
  "Leg Raise Parallel Bars": BASE + "75d2ba4ba_generated_image.png",
  "Low Cable Fly Crossovers": BASE + "c002d388b_generated_image.png",
  "Low Row (Suspension)": BASE + "8226e6b73_generated_image.png",
  "Lunge": BASE + "5e949e4ba_generated_image.png",
  "Lunge (Barbell)": BASE + "5366761a0_generated_image.png",
  "Lunge (Dumbbell)": BASE + "cc3b145e3_generated_image.png",
  "Lying Knee Raise": BASE + "7300f0c17_generated_image.png",
  "Lying Leg Curl (Machine)": BASE + "0fa6401cc_generated_image.png",
  "Lying Leg Raise": BASE + "374c80a35_generated_image.png",
  "Lying Neck Curls": BASE + "ab9af66a6_generated_image.png",
  "Lying Neck Curls (Weighted)": BASE + "8b9828baf_generated_image.png",
  "Lying Neck Extension": BASE + "d47039135_generated_image.png",
  "Lying Neck Extension (Weighted)": BASE + "cbfbce888_generated_image.png",
  "Machine Bicep Curl": BASE + "4de74edcf_generated_image.png",
  "Medicine Ball Slam": BASE + "7c7e9327f_generated_image.png",
  "Mountain Climber": BASE + "44b52b6bf_generated_image.png",
  "Muscle Up": BASE + "cab656795_generated_image.png",
  "Negative Pull Up": BASE + "c73389b1a_generated_image.png",
  "Oblique Crunch": BASE + "e555502cf_generated_image.png",
  "One Arm Push Up": BASE + "1f324e67c_generated_image.png",
  "Overhead Cable Curl": BASE + "4dcb9279d_generated_image.png",
  "Overhead Dumbbell Lunge": BASE + "e34b0c415_generated_image.png",
  "Overhead Plate Raise": BASE + "3d2ff63f6_generated_image.png",
  "Overhead Press (Barbell)": BASE + "7fa3509c2_generated_image.png",
  "Overhead Press (Dumbbell)": BASE + "0140b993d_generated_image.png",
  "Overhead Press (Smith Machine)": BASE + "1fd02496c_generated_image.png",
  "Overhead Squat (Barbell)": BASE + "f4fa54929_generated_image.png",
  "Overhead Tricep Extension (Cable)": BASE + "3f0a9dc7e_generated_image.png",
  "Overhead Tricep Extension (Dumbbell)": BASE + "7c3e86aa6_generated_image.png",
  "Overhead Tricep Extension (EZ Bar)": BASE + "f434e4cc5_generated_image.png",
  "Pause Squat (Barbell)": BASE + "3e9ac6237_generated_image.png",
  "Pendlay Row": BASE + "1b953f53a_generated_image.png",
  "Pike Push Up": BASE + "0d76b51a7_generated_image.png",
  "Pistol Squat": BASE + "718045d98_generated_image.png",
  "Plank Hip Dips": BASE + "d75cbb42d_generated_image.png",
  "Plate Pinch": BASE + "f56c848f3_generated_image.png",
  "Plyometric Push Up": BASE + "d63238fad_generated_image.png",
  "Power Snatch": BASE + "b71b66c55_generated_image.png",
  "Preacher Curl (Barbell)": BASE + "c05172540_generated_image.png",
  "Preacher Curl (Cable)": BASE + "03e7c0880_generated_image.png",
  "Preacher Curl (Dumbbell)": BASE + "38ed9d2c4_generated_image.png",
  "Preacher Curl (Machine)": BASE + "75055ebff_generated_image.png",
  "Pull Up": BASE + "ea0985177_generated_image.png",
  "Pull Up (Assisted)": BASE + "aef2781ad_generated_image.png",
  "Pull Up (Weighted)": BASE + "cd310ec06_generated_image.png",
  "Push Press": BASE + "6cfe6e086_generated_image.png",
  "Push Up": BASE + "41e2fef85_generated_image.png",
  "Push Up (Band)": BASE + "8080a8c6d_generated_image.png",
  "Push Up (Suspension)": BASE + "81773907f_generated_image.png",
  "Rack Pull": BASE + "e892c9287_generated_image.png",
  "Rear Delt Fly (Cable)": BASE + "d63f11402_generated_image.png",
  "Rear Delt Fly (Dumbbell)": BASE + "b51cbed65_generated_image.png",
  "Rear Delt Fly (Machine)": BASE + "e97cca0ce_generated_image.png",
  "Reverse Curl (Cable)": BASE + "e12fdb472_generated_image.png",
  "Reverse Curl (Barbell)": BASE + "c656cf501_generated_image.png",
  "Reverse Curl (Dumbbell)": BASE + "7b4c45eef_generated_image.png",
  "Reverse Fly (Dumbbell)": BASE + "41d2a2a45_generated_image.png",
  "Reverse Hyper Extension": BASE + "df8fcfb5a_generated_image.png",
  "Reverse Hyper (GHD)": BASE + "56e2e2663_generated_image.png",
  "Reverse Lunge": BASE + "b6f6d0cbb_generated_image.png",
  "Ring Dip": BASE + "4533d0a73_generated_image.png",
  "Ring Muscle Up": BASE + "e1d036241_generated_image.png",
  "Ring Pull Up": BASE + "08601a7a0_generated_image.png",
  "Ring Push Up": BASE + "156cbd2eb_generated_image.png",
  "Romanian Deadlift (Barbell)": BASE + "d0fdc35a0_generated_image.png",
  "Romanian Deadlift (Dumbbell)": BASE + "9780b4448_generated_image.png",
  "Romanian Deadlift Single Leg": BASE + "89b5004f4_generated_image.png",
  "Rope Climb": BASE + "b2af2f66c_generated_image.png",
  "Rowing Machine": BASE + "4cce66dc0_generated_image.png",
  "Running": BASE + "3572f4292_generated_image.png",
  "Seated Calf Raise (Machine)": BASE + "2bb20a9f2_generated_image.png",
  "Seated Dumbbell Curl": BASE + "b08fc059d_generated_image.png",
  "Seated Leg Curl (Machine)": BASE + "211497fc9_generated_image.png",
  "Seated Overhead Press (Machine)": BASE + "57a8d00d3_generated_image.png",
  "Seated Tricep Dip": BASE + "4d434b428_generated_image.png",
  "Seated Row (Machine)": BASE + "aca4d8ddc_generated_image.png",
  "Shoulder Press (Machine)": BASE + "b19be6977_generated_image.png",
  "Shrug (Dumbbell)": BASE + "e17540b3d_generated_image.png",
  "Single Arm Cable Row": BASE + "5ab31a19e_generated_image.png",
  "Single Leg Glute Bridge": BASE + "e2a01e54d_generated_image.png",
  "Sit Up": BASE + "f06a604f5_generated_image.png",
  "Skull Crusher (EZ Bar)": BASE + "042670da0_generated_image.png",
  "Skull Crusher (Dumbbell)": BASE + "019fdbb85_generated_image.png",
  "Sled Push": BASE + "bfcaff34c_generated_image.png",
  "Snatch (Barbell)": BASE + "f0cf3f2a0_generated_image.png",
  "Snatch Pull": BASE + "f54f782f3_generated_image.png",
  "Squat (Barbell)": BASE + "9b646eae3_generated_image.png",
  "Squat (Bodyweight)": BASE + "55dafa26c_generated_image.png",
  "Squat (Dumbbell)": BASE + "6bc7ca7a7_generated_image.png",
  "Squat (Band)": BASE + "e0cb9991a_generated_image.png",
  "Squat (Smith Machine)": BASE + "8eb6bca53_generated_image.png",
  "Squat Jump (Barbell)": BASE + "84fa7099d_generated_image.png",
  "Standing Calf Raise (Bodyweight)": BASE + "f3ac1fee7_generated_image.png",
  "Standing Calf Raise (Machine)": BASE + "dc49bd9a7_generated_image.png",
  "Step Up (Barbell)": BASE + "b49d7e644_generated_image.png",
  "Stiff Leg Deadlift (Barbell)": BASE + "40bdbe20d_generated_image.png",
  "Straight Arm Pulldown (Cable)": BASE + "222abfd5c_generated_image.png",
  "Sumo Squat": BASE + "6c3ffdada_generated_image.png",
  "Superman": BASE + "6a63fc78b_generated_image.png",
  "Swimming": BASE + "e4daa79f1_generated_image.png",
  "Thruster (Barbell)": BASE + "7ae557edc_generated_image.png",
  "Tire Flip": BASE + "bcd1abb79_generated_image.png",
  "Toe Touch": BASE + "f612045e1_generated_image.png",
  "Tricep Dip (Parallel Bars)": BASE + "f59716a28_generated_image.png",
  "Tricep Kickback (Dumbbell)": BASE + "a24f03f3c_generated_image.png",
  "Tricep Pushdown (Cable Bar)": BASE + "ee1a595a4_generated_image.png",
  "Tricep Pushdown (Cable Rope)": BASE + "6bd4adbe6_generated_image.png",
  "Tricep Pushdown (V-Bar)": BASE + "4abca9ebf_generated_image.png",
  "Tricep Extension (Band)": BASE + "f13fdda7d_generated_image.png",
  "Upright Row (Barbell)": BASE + "1e6180d65_generated_image.png",
  "Upright Row (Dumbbell)": BASE + "73cae2fd0_generated_image.png",
  "V-Up": BASE + "7a0c6306b_generated_image.png",
  "Wall Ball": BASE + "abc8c3a33_generated_image.png",
  "Wall Sit": BASE + "e1988bc7c_generated_image.png",
  "Wide Grip Cable Row": BASE + "fe30d458e_generated_image.png",
  "Wide Grip Pull Up": BASE + "70d2cca00_generated_image.png",
  "Wrist Curl (Barbell)": BASE + "a8036e55c_generated_image.png",
  "Wrist Curl (Dumbbell)": BASE + "41eb3da6d_generated_image.png",
  "Wrist Extension (Dumbbell)": BASE + "b214de896_generated_image.png",
  "Yoga Flow": BASE + "37da4ce2e_generated_image.png",
  "Zercher Squat": BASE + "869fbfc14_generated_image.png",
  "Zottman Curl": BASE + "3b2e158e4_generated_image.png",
};

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const db = base44.asServiceRole.entities;
    const exercises = await db.Exercise.list('-created_date', 2000);
    let updated = 0, skipped = 0;
    const notFound = [];

    for (const exercise of exercises) {
      const name = exercise.name;
      let newUrl = IMAGE_MAP[name];

      if (!newUrl) {
        const key = Object.keys(IMAGE_MAP).find(k =>
          k.toLowerCase() === name.toLowerCase() ||
          name.toLowerCase().includes(k.toLowerCase()) ||
          k.toLowerCase().includes(name.toLowerCase())
        );
        if (key) newUrl = IMAGE_MAP[key];
      }

      if (newUrl) {
        await db.Exercise.update(exercise.id, { image_url: newUrl });
        updated++;
      } else {
        notFound.push(name);
        skipped++;
      }
    }

    return Response.json({ success: true, total: exercises.length, updated, skipped, not_found: notFound });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});